### ISSUE TITLE
Top Nav Bar

### ISSUE THREAD

**Issue by chrismclarke** [OneArmyWorld/onearmy#108]
Create an interface to smoothly transition between the different pages, display avatar, and information badges (e.g. notifications, messages)

child of #106
requires #107

**Comment by chrismclarke** [comment]
Current example:
![nav1.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58d112069d5d2d20003340bb/125516c66e82c728ace21e0d46e6958c72c0cfeb9ffbb049a15ee4d6730472712807a02a29d3bb2abd172a525f5f48fd44595a47fef89b37b4f46d2ede0356b49b381d66cc2f10a5b2831abb03b8208c4c8cb4be8e4ed2a5.png)

I probably wouldn't worry much about the dropdown in the topleft as it will be quite a while until we have multiple sites supported

**Comment by mattia-io** [comment]
I think the file above is not up to date

**Comment by BenGamma** [comment]
Can you provide the current up to date version @mattia-io ? Thanks

**Comment by mattia-io** [comment]
Here is where to find latest design file (saskia is uploading the latest later tonight)
https://drive.google.com/drive/u/0/folders/1OyJmh39ojHJxs6otETNkYvDUVpAh-3aN
