### ISSUE TITLE
Improve styling of update snackbar / toast / notification

### ISSUE THREAD

**Issue by chrismclarke** [OneArmyWorld/onearmy#127]
UI Request - 

Part of the way the platform works is that everything loaded is also cached so that the site will for the most part work offline or on low-bandwidth connections (and be overall more bandwidth friendly/efficient). When a user visits the site it first loads from the cache, and then in the background checks for updates which, if available will display the next time the user visits the site

The downside to this design pattern is that the user will only ever see the most up-to-date content after a page refresh. Therefore I've added a small prompt/notification to let the user know that new content is available. Assuming we want to keep this design pattern (strongly recommended from me as I think it is in line with our low-environmental-impact ethos... why download the same web page every time you visit it right?), then we could also make this notification look/feel a bit better.

You can get a feel for the default options available for the snackbar here:
https://material-ui.com/demos/snackbars/

@mattia-io could you communicate this to the design team?

**Comment by chrismclarke** [comment]
This is the current default snackbar, I suggest we keep a similar format (message, reload button, close button).

![one army snackbar.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58d112069d5d2d20003340bb/125516c66e82c728ace21e0d46e79a9f638391a496a9ac4da55efb962854653f6b14b1247a80e03cfd1839540d0e1dff1051594caeab8c2aa5b63c76db590ae8d26f5e66da2f53fde6d640e258f075c95d8fa4bd8d46c1ed3927e08b894c3618001a8fed10.png)

**Comment by mattia-io** [comment]
Cool. Let me clear things. 

Is this only happening only if new content is published while the user is on the page?
Let me try to example it out to see if I get it right.

I am user Y and I load the page with 3 documentations. I close the page and get on with my life. Two weeks later I go back to the site, which in the meanwhile has 5 documentations. As I load the cached version, by default, I will only see 3 documentations. Leave the site again. Come back in a day, no new documentations have been uploaded, this time I see 5 documentations. 

Is that it? Did I get the functioning right?

**Comment by chrismclarke** [comment]
No, it only happens when the developers push a new build which somehow changes the way information is displayed. For example a user loads the docs page, browses a bit, gets on with life, comes back, browses some more (no change), gets back on with life again, devs decide the title should actually be larger so changes code, commits new version, person returns and will see message to say new version of platform available.

There are essentially three different caching mechanisms, one for the data (which will always just update whilst on the page, no reload necessary), one for assets like images which we may or may not want to keep cached (harder to track changes if somebody uploads a new file with same url, but I think actually this wouldn’t happen as the file uploader provides a unique one each time), and one for core javascript/html files which will require refresh on change. Note we could not have any notification, but that would mean changes to the website aren’t shown until the user happens to next visit for themselves. There’s additional intermediate options which we will likely also use so that, for example if the user hasn’t visited the site in a week it will automatically just fetch the latest version and not bother trying to load a cached (and hence no message).

The reason you want to cache the core javascript/html is because otherwise it’s quite a waste of bandwidth, always loading the exact same files for the same content (but still pretty common practice for dynamic sites).

**Comment by BenGamma** [comment]
Current implementation is done. Closing.
