### ISSUE TITLE
Create user migration functionality

### ISSUE THREAD

**Issue by chrismclarke** [OneArmyWorld/onearmy#138]
Want system that will allow users to move from wordpress database to new site. Few methods discussed and current proposal involves manually exporting users from old site, populating legacy user meta database collection and querying against when user tries to log in (creating new account and migrating data where exists). Should have minimal impact on user, but also less work than trying to keep two sites permanently in sync. Downside will need to be repeated in future if new info exists on wp site that we want migrated

child of #8

**Comment by chrismclarke** [comment]
Want system that will allow users to move from wordpress database to new site. Few methods discussed and current proposal involves manually exporting users from old site, populating legacy user meta database collection and querying against when user tries to log in (creating new account and migrating data where exists). Should have minimal impact on user, but also less work than trying to keep two sites permanently in sync. Downside will need to be repeated in future if new info exists on wp site that we want migrated

**Comment by mundane140** [comment]
Hey! 
Could you elaborate a little on "manually exporting users"?

**Comment by chrismclarke** [comment]
legacy users and hashed passwords can be pulled from the old (wordpress) mysql database, need to be cleaned slightly (issues with different hashing strategies, special characters etc.), and then can be populated into the new database. They can't be used directly from here, but the current mechanism takes a user login attempt and if no user exists cross checks the username from the migrated list, validates whether the password they have just submitted matches the hashed pw, and migrates the user over if successful. So from the users' point of view they simply type their old email and password and will be logged into the new system with all their data migrated.

why do you ask?

**Comment by mundane140** [comment]
Just trying to contribute. 😁

Correct me if I am wrong.
- Migration = fetch credentials from old datastore -> transformation on password -> save in new datastore -> deletion of data from the old datastore.
- Login attempt -> check in old datastore -> perform migration, if record exists in old datastore, else check in new datastore

**Comment by mundane140** [comment]
Also, I think, a possible solution could be,
-

**Comment by chrismclarke** [comment]
Contributions most welcome, we have a mix of both large and minor unassigned features which we would be keen to have people work on.

In order to effectively manage and coordinate with potential contributors we have an induction process outlined here: https://github.com/OneArmyWorld/onearmy/blob/dev/CONTRIBUTING.md

If you could please take a short amount of time to review the guidance and use the contact form to let us know a little bit more about what you hope to contribute to the project then we will be able to work together to try and make the best use of the time you have.

Many thanks!
