### ISSUE TITLE
Delete step confirmation

### ISSUE THREAD

**Issue by chrismclarke** [OneArmyWorld/onearmy#140]
Disappears very quickly, would be good to have confirmation and later animation
child of #3

**Comment by BenGamma** [comment]
popup design here : https://www.figma.com/file/PzJv2O0oEFWMUGOuFkBES83h/PP_Documentation?node-id=0%3A1

**Comment by chrismclarke** [comment]
Material dialog component: https://material-ui.com/demos/dialogs/
I like the slide in one personally

**Comment by BenGamma** [comment]
related to #44
