### ISSUE TITLE
General guidance for design team

### ISSUE THREAD

**Issue by chrismclarke** [OneArmyWorld/onearmy#142]
As a quick piece of info:

# Links
The component library we are building on top of can be found here:
https://material-ui.com/demos/app-bar/

# Issues
If you want to format the text that appears in an issue see the guidance in #2

We have a labels system that is mostly designed for dev use, it's not likely that you will need to tag things (as everything is automatically tagged as design) - but if you do want to create additional labels then feel free (but limit to a single colour tag for all design-related issues)

If you know who is working on a specific development item then feel free to assign them to the issue here, otherwise by default assign @chrismclarke who will organise

You can also use the epics/modules column to add input related to a specific area if wanted (by default these should already have the active devs involved)

# Any other queries
Just put in the thread here and I'm happy to respond

**Comment by preciousplastic** [comment]
Testing contributing devs workflow. @BenGamma it works :)

**Comment by chrismclarke** [comment]
I think people seem happy enough with current communication flow and are on top of the platform so going to close this
