### ISSUE TITLE
Documentation: As a user I want to select multiple pics when uploading to a step

### ISSUE THREAD

**Issue by mattia-io** [OneArmyWorld/onearmy#152]
child of #3

**Comment by mattia-io** [comment]
Currently, as I click "upload pic" there is a pop-up window but I can only select one pic at a time

**Comment by BenGamma** [comment]
Yes I understand but how to order the images in the step if we can select multiple at once ?

**Comment by mattia-io** [comment]
Automatically by file name. 
And ideally eventually as a user you should be able to move pics up and down within a step

**Comment by BenGamma** [comment]
Yes that would be a nice feature but I'm not sure that it's a priority now. If you agree we can keep it in backlog for iteration 2.

**Comment by mattia-io** [comment]
sure

**Comment by BenGamma** [comment]
After redesign, this is no longer up to date. Pictures of a step are selected one by one to allow a display order of the pictures.
Closing.
