### ISSUE TITLE
Documentation: pics bug

### ISSUE THREAD

**Issue by mattia-io** [OneArmyWorld/onearmy#153]
I was trying to upload a new documentation but I encountered multiple bugs when uploading images. Couldn't seem to work out a pattern there. Images previously uploaded would suddenly disappear (multiple at a time). Had to go back and forth to check all ics were still there. Super weird.

child of #3

**Comment by BenGamma** [comment]
child of #3

**Comment by BenGamma** [comment]
It's hard to understand what append here, can you explain how to reproduce the bug you encounter ?

**Comment by mattia-io** [comment]
Probably just have to try upload a documentation with multiple steps each including multiple pics.. As I said I can't understand the pattern to help reproduce it

**Comment by chrismclarke** [comment]
Hopefully this will be fixed with the update I've made to docs file upload and delete. Merge requested (pending @BenGamma  review), will let you know when it's live for testing
