### ISSUE TITLE
Documentation: Move pics order in each step

### ISSUE THREAD

**Issue by mattia-io** [OneArmyWorld/onearmy#154]
As I was using the tool I found myself needing to move pics up and down within each step.
child of #3

**Comment by BenGamma** [comment]
this will be fixed with #118

**Comment by chrismclarke** [comment]
so #118 deletes pictures, although does that mean you also want a way to drag/drop pictures and change the order they appear in? That would definitely be tricker (but not impossible)

**Comment by BenGamma** [comment]
Yes that is the behavior wanted. But since #118 has been implemented, I move this to backlog as it is a new feature.

**Comment by chrismclarke** [comment]
merge into #227
