### ISSUE TITLE
do the call to get all tutorial only on tutorial list page

### ISSUE THREAD

**Issue by BenGamma** [OneArmyWorld/onearmy#156]
For now the tutorial list is called from firebase everytime we load a page from /docs. So even when I'm on /docs/create, where I don't need to see any of the tutorials, the call to our database is fired.
The correct behavior would be to call for all tutorials only when we need to list them, on : /docs/list.
We should change the call for store method `getDocList` from the page/Docs/Docs.ts file to page/Docs/Content/TutorialList/TutorialList.ts

**Comment by chrismclarke** [comment]
I think it's actually ok. 

The problem with moving to the list component level is that would mean the request is fired every time the list is shown (e.g. if you click on a doc and then go back it will run the request again, which is really inefficient).

Currently it is fired once no matter where you start (list, doc or create), but then the data persists however you navigate around the sections. This makes extra sense if you think that even if a user starts on create or an individual doc, they will probably go back to the full list at some point so it's nice that the data is already all there.

We might want to revisit this in the future if we implement additional caching on the client side. 

closing for now

**Comment by BenGamma** [comment]
Ok so it's the loading bar that appear when you navigate on top of the /docs pages that confuse me, my bad !

**Comment by chrismclarke** [comment]
Oh, yeah we should do something about that, only show the bar when making a server request and not when just waiting to load perhaps
