### ISSUE TITLE
add custom error handler

### ISSUE THREAD

**Issue by chrismclarke** [OneArmyWorld/onearmy#168]
would be good to record errors on sentry (or similar) and ensure they aren't seen on live sites

**Comment by tx4x** [comment]
hi,
what kind of errors you'd like to record ? tracing uncaught errors can get quickly complex. there are also a few browser quirks (FF <11, safari) which have to be treated explicitly. anyway, it's a full day of work and near 2 pages of dense code ...

**Comment by chrismclarke** [comment]
In my experience it need not be so complicated. In other projects I've simply set up a free dashboard at [sentry.io](https://sentry.io), and used their `Raven` javascript tooling to automatically catch and trace otherwise uncaught errors, and push to the dashboard alongside custom meta that I think would be useful for debugging (e.g. state variables). This is more like 5-10 lines of code in total, and could also easily be extended to also work with react's own componentDidCatch mechanism to aggregate errors on individual components.

A 10 minute search on google and I don't see any strong alternatives (open to suggestion). Also I've only ever used with Angular projects (and it works very well), I see there is documentation for React so I assume all would be fairly straight forward for anyone interested in implementing.

**Comment by tx4x** [comment]
hey, ok lets go for it :-)
I understand using this functionality is rather at certain moments. may be it makes easier to define what to inject and when and how, as outline.
btw. writing a good opt-in agent to trace errors (stack-trace as well) requires quite a good amount of knowledge about browsers. the code we did was 80% about browser quirks and the rest about onError and stack-traces

**Comment by chrismclarke** [comment]
yeah that doesn't sound very fun at all! But maybe a battle worth fighting in the future if we really see a rise in user numbers, devices and browsers

**Comment by tx4x** [comment]
lol, let me check the sentry.io agent but I guess it's complete and doesn't add too much size. I have some spare time to get this done, til we proceeded with the tinymce merge and so we make the final steps afterwards (mention plugin, link, doc, whatever picker, multiple image uploads, image resize, etc...)
g

**Comment by tx4x** [comment]
ok, I checked. please :
1. create sentry.io token
2. let m know how you want this, ie: as HOC for any component, or as simple class implementation as suggested by sentry :
```js
// Sentry.init({
//  dsn: "https://6964fb7e9992466aa738d39148263943@sentry.io/1396281"
// });
// should have been called before using it here
// ideally before even rendering your react app 

class ExampleBoundary extends Component {
    constructor(props) {
        super(props);
        this.state = { error: null };
    }

    componentDidCatch(error, errorInfo) {
      this.setState({ error });
      Sentry.withScope(scope => {
        Object.keys(errorInfo).forEach(key => {
          scope.setExtra(key, errorInfo[key]);
        });
        Sentry.captureException(error);
      });
    }

    render() {
        if (this.state.error) {
            //render fallback UI
            return (
              <a onClick={() => Sentry.showReportDialog()}>Report feedback</a>
            );
        } else {
            //when there's not an error, render children untouched
            return this.props.children;
        }
    }
}
```

**Comment by chrismclarke** [comment]
I think it makes most sense for initially you to create your own account and use the token from that so that you have full access to the dashboard, then we can transfer ownership to a shared email later once working correctly (it would be good to avoid paying for a team subscription unless felt necessary at a later point).

I don't have a strong opinion or knowledge of how best to implement so feel free to experiment however you feel best.

**Comment by tx4x** [comment]
hi,
so i finished the first slice

- sentry catches all errors but also wraps the console object (which is annoying because you have an altered stack / display in the chrome - dev - tools. i have put a quick toggle in src/config 'sendErrors' to disable this via url '?captureException=false'
- i have put an Error Boundary component at the root of the app
- i re-exported the sentry.io manual log functions  in https://github.com/tx4x/onearmy/blob/error-handler/src/common/errors.ts so if needed this can be wrapped further as decorators or common logging functions

I have to wait for dev-notice (#272 ) and mobx (#276 ) to make a PR for this.

**Comment by chrismclarke** [comment]
sounds great, yeah the PRs have been slow today as some challenging refactoring for backend functions needed (still WiP, but 90% there), and lots of conflicts to sort as quite a bit of work done across the different branches. Should have #272 and #276 in by tomorrow though

**Comment by chrismclarke** [comment]
New account setup for onearmy, dsn info has been added to `src/config` for dev/staging and prod sites and pushed to the master branch.

For anybody who would like to access the dashboard I'm happy to share the details (unique password for platform and no billing setup)

Can login as hello@onearmy.world, pw: 5wcigHBuV8tXMez

I'm guessing now the other PRs have been merged this should be good to go @tx4x?

**Comment by chrismclarke** [comment]
Also if anybody just wants to receive the weekly error summary report via email I can setup a label and forwarding rule for the email inbox

**Comment by tx4x** [comment]
@chrismclarke, great, i am back tomorrow with a PR for that.
