### ISSUE TITLE
Remove uploaded files when documentation not saved

### ISSUE THREAD

**Issue by chrismclarke** [OneArmyWorld/onearmy#177]
child of #3
Did partial implementation using refs and uploadedfile component, however doesn't delete full folder reference on server (leaves empty folder), and messy when requiring second set of refs for steps, so propose trying to do something server-side instead

**Comment by BenGamma** [comment]
Where are we on this. Still sounds relevant to me to implement.

**Comment by chrismclarke** [comment]
no longer relevant as all files uploaded on submit
