### ISSUE TITLE
Styled components - material-ui interoperability issue

### ISSUE THREAD

**Issue by chrismclarke** [OneArmyWorld/onearmy#179]
As material-ui injects its stylings into head styled-components fails to override. Workarounds include marking things as '!important' or wrapping '&&' before code (see Tags/elements.tsx for examples). It would be better if this wasn't required.

Tried implementing solution here but failed: 
https://material-ui.com/customization/css-in-js/#css-injection-order

Suggest waiting until v4 of material-ui where they plan different possible solution (or could try again)

**Comment by BenGamma** [comment]
For now using this workaround if needed https://github.com/styled-components/styled-components/issues/1253#issuecomment-337871693
Closing.
