### ISSUE TITLE
cover image disapear on title field click/focus

### ISSUE THREAD

**Issue by BenGamma** [OneArmyWorld/onearmy#180]
After merge of the branch #118---image-delete this bug appear.
To reproduce :
- upload a cover image before filling others steps
- click on the tutorial title field to add a title. The cover image disapear at this moment.
Probably related to a forceUpdate() or a non wanted render() of the dom.

**Comment by chrismclarke** [comment]
it's the custom onblur function which was used to strip characters. As it happens we no longer need this as it's done onsubmit.

**Comment by chrismclarke** [comment]
should be fixed with efaff9c173ee1928c33fa966ddc278e2972eda11
