### ISSUE TITLE
create global site navbar

### ISSUE THREAD

**Issue by chrismclarke** [OneArmyWorld/onearmy#184]
*Updated 06-02-19 (Mattia)*

Overview:
We need to create the navbar for the global site https://onearmy.world/ 
This navbar will enable users to navigate to:
-Projects
-About
-Community

![Screenshot 2019-02-06 at 09.43.23.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5beadf2e66e72100136491d9/125516c66e82c728ace21e0d46db978826878dba87e6ab03f60da1cd6416753e7952e32a64c5b371f116284f5d5c5cb053181d1ba6acda6fb4bc2e75d80d58be8064597c946f14adbb821fb950bf218e4c87b7ae965e82b96371b8d6d6056b5c17129bfe5a3fa19c4fc15cf249e74c52a2153f71ab.png)

Latest prototype:
Prototype
https://sketch.cloud/s/KGerV/VrVvaPw/play

Originals + Screens
https://drive.google.com/drive/u/0/folders/1OyJmh39ojHJxs6otETNkYvDUVpAh-3aN

Epics:
https://docs.google.com/spreadsheets/d/1pkLRKCbQiJOtQwWEhVNgSTvDWf5SnVAz10vMo4k-LNg/edit#gid=0

Any questions post in the comments

child of #106

**Comment by mattia-io** [comment]
@harrier91 is working on this 💪
Make sure to check this other issue related to this #186

**Comment by chrismclarke** [comment]
cool, pr sent to put login system back in and will leave to @harrier91 for styling (I'm hoping that's the same Andrea that I've been talking to on slack right?)

**Comment by chrismclarke** [comment]
wait my bad, Andrea is community navbar... all cool

**Comment by chrismclarke** [comment]
any update on this @harrier91?

**Comment by mattia-io** [comment]
@harrier91 I am gonna have to assign this issue to someone else for now unless you will confirm you want to deliver this

**Comment by harrier91** [comment]
Some changes I did were merged already into master, I'm not sure what more should be done about it. Which is the definition of done of this task? Because I think some pages are not ready yet

**Comment by mattia-io** [comment]
Hey @harrier91 thanks!

@chrismclarke is there anywhere we can check this? 
Have the global site pages (even placeholders) already been created?

**Comment by BenGamma** [comment]
@harrier91 I can't find any PR from you, can you point us to your changes ?

As discussed in #186 the behavior here is to create the navbar of the landing page on onearmy.world (eg mockup on thread top). On click on the top right button, user is redirected to community.onearmy.world

**Comment by harrier91** [comment]
I was referring to this one, but I've just noticed that it was closed, not merged, sorry:

https://github.com/OneArmyWorld/onearmy/pull/376

Anyway that should work as switch if I understood right. 
In case that's not the correct change feel free to assign this to someone else, as I don't have much time next weeks.

**Comment by chrismclarke** [comment]
> Hey @harrier91 thanks!
> 
> @chrismclarke is there anywhere we can check this?
> Have the global site pages (even placeholders) already been created?

I'm not fully up to date on this so will leave for @BenGamma to resolve as he seems to have been involved with the previous PR. Thanks for the update @harrier91 .
