### ISSUE TITLE
ensure slugs are unique

### ISSUE THREAD

**Issue by chrismclarke** [OneArmyWorld/onearmy#192]
Have multiple 'test' docs which now can't be displayed as newer db entry with slug 'test' exists
child of #103

**Comment by BenGamma** [comment]
related to #90

**Comment by chrismclarke** [comment]
have implemented for discussions, will want to use same logic when refactoring other stores

**Comment by martisj** [comment]
I am going to have a stab at this on the airplane to Norway. In case anyone wants to assign this to me 👏

**Comment by chrismclarke** [comment]
Great, I've removed the `help wanted` label and sent an invite to you to join the project so I can officially assign. Let me know when you've joined.

As for the slugs, the database store object has a function called `queryCollection` which can be used the find documents where slug == ..., and use the length of the return to determine whether unique or not.

**Comment by chrismclarke** [comment]
(the queryCollection in this implementation builds directly on top of firestore's own methods, with more info here: https://firebase.google.com/docs/firestore/query-data/queries)

The reason for separation is in case we ever want to migrate to a different database provider

**Comment by martisj** [comment]
> Great, I've removed the `help wanted` label and sent an invite to you to join the project so I can officially assign. Let me know when you've joined.

There we go! I've assigned myself and will sit down after work today 👏
