### ISSUE TITLE
Create user registration component

### ISSUE THREAD

**Issue by chrismclarke** [OneArmyWorld/onearmy#20]
Should have place to specify required info: email, pw (+confirmation). Additional info likely also such as first name, last name (see what is currently in Dave Hakkens signup). This component should also double as profile update, providing option to either register or update info.
child of #8

**Comment by chrismclarke** [comment]
note, will also want to populate db with user meta

**Comment by kopecms** [comment]
I would love to start proggress on it ; ) @mattia-io @chrismclarke ok?

**Comment by chrismclarke** [comment]
That would be awesome! I'm not sure if the full mockup has been made for this yet but will check and get back to you. If not you could still start building some of the core functionality. I'd suggest using react-final-form for form data handling as that is what is already in the project

**Comment by chrismclarke** [comment]
Another good place to start work might be a profile picture uploader/editor. We have a couple different implementations of file uploads which could work totally fine (see the how-tos), or if you wanted a richer experience you could explore options for a simple image editor (e.g. cropping). Totally optional though, will need to check with @mattia-io whether this would be a core feature wanted on the platform (I know he's away for the next couple days but should be back by early next week)

**Comment by kopecms** [comment]
Should sing up form be on separete page? Is there way to access firebase database localy (I haven't look much into this technology yet)? And what about workflow: should PR be full feature closing issue or issue can have some PRs?

**Comment by chrismclarke** [comment]
I  think to streamline development and testing it probably makes sense to have a separate page, we could always move later if needed.

For the dev site firebase is setup and ready to work with, you can see how some pieces of work interact directly with it via import of the `utils/firebase` helper, although I'm slowly trying to migrate to use a middle layer `Database` object which data stores will interact directly with. There is already a user.store which you could build on.

If confused the difference between LegacyUser and User models, that is because we will be migrating user logins and profiles from the old site. This requires a user to attempt login first using their wordpress username and password. This is then cross-checked against the legacy user database collection (which stores an encrypted version of their password, so passes the pw input through the same encryption protocol to see if output matches as a confirmation that this person is the owner of the old account)

As it's a fairly isolated piece of work feel free to handle PR however best works for you. We make an active effort to review all PRs each Tuesday (and whenever else we can find time). This is probably easier if the PRs aren't huge, but again we wouldn't want to be a bottleneck for your work so just use your judgement. If there are multiple PRs a naming system like feat/user-registration, feat/user-registration-some-part would probably make our lives a bit easier too

**Comment by chrismclarke** [comment]
As a technology hopefully you will find firebase quick to learn. A few points of interest:
1) They have 2 different database system, the mostly legacy firebase 'real-time database' and the newer 'firestore' database. We are using firestore
2) It stores data in the format `/collection/doc` where a collection is simply a list of json objects. Any doc can also have a subcollection, e.g `/discussions/abc1/comments/...`, so this is how data would be organised that would otherwise want to be connected via primary/foreign keys,

**Comment by chrismclarke** [comment]
If you want access to the database dashboard just let me know your email for google account, either on here, slack or email: chris.m.clarke@live.co.uk and I can add you to the project

**Comment by BenGamma** [comment]
Done with #373, closing.
