### ISSUE TITLE
When should we next push to live?

### ISSUE THREAD

**Issue by chrismclarke** [OneArmyWorld/onearmy#200]
@Mattia-io
There's a bunch of changes on the dev site which aren't finished, but I was thinking we should still consider pushing them to the live site (onearmy.world) soon. 

Also now that there is a navbar we should consider how things should be displayed on sub-sites (i.e. https://documentation.preciousplastic.org) - I'm assuming the docs page without a navbar correct?

As an extra note to myself, the image compression is now working nicely on dev, so when we push to live we should bring the updated functions too.

requires #84

**Comment by chrismclarke** [comment]
merge complete and functions updated

Need to test (https://onearmy.world) - note, will require manual refresh after a few seconds as also includes the code to prompt when new version available

**Comment by BenGamma** [comment]
Push on production with https://github.com/OneArmyWorld/onearmy/pull/231
