### ISSUE TITLE
create comments component

### ISSUE THREAD

**Issue by BenGamma** [OneArmyWorld/onearmy#209]
The purpose of this thread is to share opinions on this feature and found the best solution available out there to make it.

The next discussion module we are building will allow users to comment the post. We want to be able to reply to comments.

Here is a mockup of how we want it to be :

![v9 discussions_question_9 1 19](https://user-images.githubusercontent.com/4993215/50976563-98d03800-14f0-11e9-9ebd-d5315f782bb1.png)

child of #213

**Comment by BenGamma** [comment]
This issue is about finding the best solution for commenting a discussion post or answer a Q&A question.
Related to https://github.com/OneArmyWorld/onearmy/issues/211

**Comment by chrismclarke** [comment]
Mockups look great! I think last time we spoke it was agreed that would most likely easiest to build from scratch than try implement a pre-built system. Judging by the mockups I think I still mostly stand by this - questions/comments can be simple pushes to the database and we can add relevant database cloud functions to send notifications etc. 

If I remember correctly @BenGamma had you already investigated wysiwyg editors? I think we might have discussed draft.js (which I really like), but perhaps are now thinking markdown would be better? I'm easy either way.
