### ISSUE TITLE
change top section text in onboarding bar (dark blue bar below navigation) depending on nav

### ISSUE THREAD

**Issue by BenGamma** [OneArmyWorld/onearmy#212]
Depending on your navigation, we'll display a different onboarding bar under the top navigation, to inform the user on which section he is.

<img width="1407" alt="capture d ecran 2019-01-11 a 12 26 13" src="https://user-images.githubusercontent.com/4993215/51031218-287ef080-159c-11e9-9c5d-83410a9cc9de.png">

The text contained in the onboarding bar is not figured out yet, so it can just be the name of the section e.g. (newsfeed, how to, discussion)

child of #106

**Comment by mattia-io** [comment]
I think we can wait on this for the final UI from nico.. navbar is ok as it is for now with the raw functionalities in place

**Comment by suvya** [comment]
I can take this up @mattia-io

**Comment by mattia-io** [comment]
Nice one @suvya 🙌

**Comment by mattia-io** [comment]
@suvya any rough idea how long this would take?
