### ISSUE TITLE
Module - Discussions

### ISSUE THREAD

**Issue by mattia-io** [OneArmyWorld/onearmy#213]
**Updated 18-03-19 (Ben Gamma)**

**Overview:**
The discussion page is where people in our community will meet, connect, chat, talk and ask questions. Here users will find a list of posts created by other users. Posts can be of two types: Discussions or Q&A. 
Discussions are to describe a process, idea, machine, hack or anything else.
Q&A is for users to post open questions for the rest of the community (think stackoverflow). Creator of the question will choose a correct answer.

In this module we have 3 main pages: 
- Discussions overview (#402)
- Talk post (#409)
- Q&A post (#409)
- Create post

**Latest prototype:**
Prototype
https://www.figma.com/proto/OZ5xbZYR4ZKNBijrs9kPJnbu/OA_UX_v02?node-id=473%3A4525&viewport=3107%2C1897%2C1&scaling=min-zoom&redirected=1

**Epics:**
https://docs.google.com/spreadsheets/d/1pkLRKCbQiJOtQwWEhVNgSTvDWf5SnVAz10vMo4k-LNg/edit#gid=0

Any questions post in the comments

**Comment by chrismclarke** [comment]
mocks updates so front-end guys should be able to start more work on list and view pages

**Comment by chrismclarke** [comment]
next priority will be to add data stores and methods to control how the database is interacted with. It will likely follow a similar format to the how-to page, so might also be a good opportunity to refactor some of that code for reuse

**Comment by chrismclarke** [comment]
List component updated by @tx4x (pull #358). Some comments from the PR include to-dos for:
- Filters (track in separate #216)
- Expected functionality of individual elements (will comment below)
- Avatar component (track in #351)
- Search (track in #328)
- Server Paging (non-issue for now, might revisit in future)
- Standardising some of naming and interface (linked to #346, minor nit)

**Comment by chrismclarke** [comment]
@mattia-io, penny for your thoughts 💰
 
We've had an update to the discussions list from @tx4x, still plenty more planned in terms of styling (few people working on it) and filters/tags/search will be coming in soon, but in the meantime there's an extra question about how we want the different elements to behave:

Currently wherever you click on a discussion list element it will take you to the page displaying the full discussion. Are there any other interactions that you might want? E.g., clicking on the avatar takes you to the profile of that user? or clicking a tag takes you to everything related to that tag throughout the site?/or other discussions tagged the same? (or nothing) etc.?

![image](https://user-images.githubusercontent.com/10515065/53375743-feb73880-3953-11e9-97f3-1218dfab7e1a.png)

**Comment by tx4x** [comment]
i think there should be at least a jump to the latest reply & media, also clicking author name is a must :-)

**Comment by mattia-io** [comment]
Hey people :)
Thanks for this. So currently working on a more robust prototype that can answer all your questions in a more clear and precise manner. For now let's keep it as simple as possible (MVP):
-Yep, the whole discussion element should be clickable
-Avatar to profile page 100%
-Still talking over the categories and tags.. more coming soon

**Comment by tx4x** [comment]
@mattia-io : please don't forget jump to last reply button (number of comments will do too), that's pretty much one of the most annoying now in the forum. 

also: the current mock suggest a very rigid/old way of showing post. i think in modern times like now we could deserve a little more smart views : hot now, most viewed, most voted, etc... pretty much basic but yet an absolute must :-)

**Comment by mattia-io** [comment]
hey @tx4x I'll bring the jump to last reply/comment up with the UX.. promise :)

About the showing post we do most recent, most useful and most comments.. aybe the mocks don't show it properly.. that's why we're working on better mockups/prototype

**Comment by BenGamma** [comment]
This is on hold for now. Will reopen when appropriate in a close futur.
