### ISSUE TITLE
Discussion overview - ListRow component

### ISSUE THREAD

**Issue by BenGamma** [OneArmyWorld/onearmy#214]
On the discussion page, we need to create a row containing all the informations about a post, e.g. this mockup :

<img width="1161" alt="capture d ecran 2019-01-11 a 12 42 40" src="https://user-images.githubusercontent.com/4993215/51031920-6da42200-159e-11e9-95e9-a9d8944f78f7.png">

This row is part of the list of posts.

For now we'll based the post data on hardcoded mock. We'll need to create a new mock file inside the `mocks/` folder and then import it to the row.

child of #213

**Comment by chrismclarke** [comment]
I can see this most likely breaking down into separate components for user avatar, tag link, and then everything else. I think the user avatar might already be part of the login component but will confirm when next sitting down with the project (hopefully next weekend or so)

**Comment by BenGamma** [comment]
Updated mockups :
<img width="1238" alt="Capture d’écran 2019-03-15 à 11 28 38" src="https://user-images.githubusercontent.com/4993215/54428461-dbdf9f00-471d-11e9-9fb3-c7941b46d3cb.png">

**Comment by BenGamma** [comment]
Hey @kopecms did you started working on this ?

**Comment by kopecms** [comment]
yeah but I didn't finished and right now I am out for a month without computer. sorry I forgot to change status here
