### ISSUE TITLE
Discussion post list

### ISSUE THREAD

**Issue by BenGamma** [OneArmyWorld/onearmy#215]
We want to list all the posts available in the discussion section, e.g. mockup :

![__Discussions_landing](https://user-images.githubusercontent.com/4993215/54366058-476b3300-4670-11e9-91a7-0868de021976.png)

Use the mocks data available in the `mocks/mock.posts.tsx` folder to get all the post.

child of #213

**Comment by chrismclarke** [comment]
Again really like the mockups, I don't think we've implemented any sortable table structure yet so it might be a good place to start investigation (I think there probably is already material table or similar, and plenty of third party packages depending on how much we want them to be able to do... I would suggest simpler is better).

**Comment by BenGamma** [comment]
I put this lib on the side a few weeks ago https://github.com/bvaughn/react-virtualized

It may be a bit overkill for what we want to do. Needs investigation.

**Comment by tx4x** [comment]
hey,
after searching long for a state-of-the-art (tree, keyboard navigation, sort, column toggles,etc...) grid component I end up with react/ts/material-ui friendly lib : https://devexpress.github.io/devextreme-reactive/react/grid/demos/featured/tree-data/

it's rock solid but has license issues to check first. 

the built-in tree renderer  can be tweaked for discussion replies as well.

**Comment by tx4x** [comment]
@here : please let me know what lib you want, i have every day 4 hours free for the one-army...
thanks :-)

**Comment by chrismclarke** [comment]
I think we're planning to try and nail down the database structure this week and will update the mocks. I had assumed we'd be mostly creating our own implementation but happy to explore solutions that already exist. The link you sent looks really promising, @BenGamma you might want to take a look. I reviewed the licence and fine for our purposes (non-commercial, non-competitive)

**Comment by BenGamma** [comment]
Yep looks promising, you can start an integration of this lib with our current `mocks/mock.posts.tsx` datas.
For the discussion replies it can also be an option, but as chris said we are working on the database structure this week and will create related issues when ready.
Good to ear that you have that much time to dedicate to the projet, will do our best to provide clear issues and goals !

**Comment by tx4x** [comment]
right. i am happy to make this one :-) is there a parent epic in waffle for this ? and, if you don't mind i will do only a first slice, i am still a little puzzled about that styled-components to evtl. replace material-ui import. those things are indeed a little unclear to me (ie: shared components). anyway, no show stopper for me, so don't worry too much about  :-)
g

**Comment by tx4x** [comment]
@here,
if you don't mind , i will add support for different 'views', ie : one would be a standard list and the other will have larger tiles/cards showing pictures.

**Comment by chrismclarke** [comment]
I don't think there would be pictures associated with each discussion thread so that might not be worth too much effort, although I could imagine a toggle between grid and list being useful if it could also be reused on other components like the how tos perhaps.

**Comment by tx4x** [comment]
yup, that's correct, for around 30%, mostly uninteresting stuff :-) 

anyway, i'd love to have such view for posts with a high amount of activity/likes/links/media, etc.. 
another would be to see only the posts of selected users, which i'd consider as 'my network' view ;-)

but ok, let's see where this goes, in the mean-time i keep pushing for it , seeing all related uploads/links for a selected tag/category will be definitely useful nonetheless, compared to a pretty old-schoold rigid list only ;-)

**Comment by chrismclarke** [comment]
Two of the next big pieces of work are implementing the tagging/filter system as well as search, I think that's where we could really implement some nice ways to help users find and engage with content easier

**Comment by tx4x** [comment]
yeah, good news about this : i 've plenty of code for this already, exactly for this lib (including a visual filter builder). it doesn't take much to build 'perspectives' or presets on top, user or admin defined, we're are getting there :-)

**Comment by tx4x** [comment]
@BenGamma there is no mocks/mock.posts.tsx, i guess its rather src/mocks/discussions.mock ?

**Comment by BenGamma** [comment]
@tx4x yes that's it ! we are working on the data structure right now, so consider that it will change in a close futur.

**Comment by tx4x** [comment]
ok, will wait then :-)

![image](https://user-images.githubusercontent.com/1205100/53087180-d28c5980-3506-11e9-8286-c3acce2163a3.png)

there is some more meta data i may need pre-calculated for all the posts: 
- user - names
- tag - names, category names - and their icons (if)
- latest reply time
- post image (can be the first or the last)
- timestamps for : created, updated, last reply
- last replying user (name, avatar)

**Comment by tx4x** [comment]
ah and all the other stuff is also unclear : paging, request caching but no show stopper
g

**Comment by tx4x** [comment]
ok, [basics are done](https://github.com/tx4x/onearmy/tree/215-discussion-post-list) : 

![image](https://user-images.githubusercontent.com/1205100/53089776-cb1c7e80-350d-11e9-96be-2c2ec1f6fff7.png)

so you can play around and see how the grid component has to be feeded. devexpress-react-grid has quite some plugins. 

i will head over to tinymce plugins (mention, link picker) for now

**Comment by tx4x** [comment]
I added a filter system (proposal), the format is RPC friendly,  [see here](https://github.com/tx4x/onearmy/blob/215-discussion-post-list/src/pages/Discussions/common/filters.ts#L238) and support AND and OR.

this allows you to quickly setup filters, ie: recent friend posts, with high activity, etc..

**Comment by chrismclarke** [comment]
I really like it, seems like nice and flexible way to implement an advanced filter system. The other mechanism for filtering content will be through a generic 'search' box which will hook up to a search engine and provide deeper content searches and ranking algorithms. If you'd be interested in that feature also there's more info in #328

**Comment by tx4x** [comment]
thanks, will look at it. for now I am trying to implement the mockups with that: ie select multiple tags/categories & search text.

**Comment by chrismclarke** [comment]
discussions backend updated (pull #332). @BenGamma , shouldn't require proper review (testing and working as intended, also fixed the simple filter system), but will require `yarn install`. Any more work on the list should be done taking the slightly changed structures into account (mostly just correcting the timestamp format).

**Comment by chrismclarke** [comment]
plan to bind the create/edit workflow to the database tomorrow which should make it easier to create more substantial testing data (e.g. with correct tags, projects etc.) for use with filter system

**Comment by tx4x** [comment]
hey guys, @chrismclarke I have unexpected visitors, I am back with PRs monday then :-)
g

**Comment by tx4x** [comment]
@chrismclarke : which branch i have to take as input ? there is a module-discussion, and another module-discussion-backend

**Comment by chrismclarke** [comment]
the discussion backend is most advanced and refactors quite a bit of the discussions more generally, there's a pr open for review but see some comments have been made so will just merge everything and tidy up now

**Comment by chrismclarke** [comment]
ok merged, feel free to pull from master

**Comment by chrismclarke** [comment]
Also just to note, the update changes mobx from 5.x to 4.x (both actively supported), so will require a yarn install

**Comment by tx4x** [comment]
okeey, i checked all related branches and commits and I came to the conclusion :

- my work on the new list module should be reviewed and merged as soon as possible (can be there monday)
- having those json friendly filter expression in place, getting hands on agolia search but also the filter bar seems pretty easy and straight forward then.

btw. the proposed filter system supports a combination of search text and multiple categories and tags as well...

what's your suggestion, I make a PR to the discussion-backend branch ?

**Comment by chrismclarke** [comment]
Yeah things are getting a little bit messy as quite a few people are working on things related to discussions, with a fair mix of new features and refactoring. Sure, make the PR to discussions-backend, I'll review and merge with my code and the main discussions branch, before making a complete pr for review on Tuesday.

**Comment by tx4x** [comment]
@BenGamma things got here a little bumpy, i have to manage 2 other teams on the side so i have only 12 hours per week for the next weeks ;-) 
however, this week, in this order:
1. filter bar (native select widget or material ? ) implementation : basics only, just to get stuff working
2. use the filter system to provide some 'view' presents : default, most liked, etc.. i will have to look into the mockups again
3. the rest of the week i still need to get my head into agolia, things aren't that easy: request caching, scoring (if that exists, for title & description), don't bother for now but's more about toying around
see you in a bit
g

**Comment by BenGamma** [comment]
No worries, it's already helping a lot :)

1. Would prefer if you start working with the `src/pages/common/FilterBar` which uses the `src/components/Selector` instead of material-ui
2. Are you talking about the list sorting or the filter sorting ? Because I need to clarify list sorting with design team, meeting planed for tomorow morning, I'll keep you updated with the needed view in this thread.
3. About algolia yes I would be curious to have your feedback after some tests. Before going into advanced usage such as request caching, automated content indexing when a post is saved and the ability to search for it would be a nice first step.

**Comment by tx4x** [comment]
great, thanks @BenGamma

**Comment by tx4x** [comment]
2. yes, filtering (#244 ) will be implemented as follows: 

- the filterbar will emit an event with a payload {prop:'categories|projects|tags' , value: 'selected value' }
- the very payload will be transformed to an Boolean filter expression : 

```js
{
filters:[
 {
  prop: 'category',
    filter: {
      op: 'equals',
      value: 'selected category',
    }
}]
```
that expression will be consumed by src/pages/Discussions/common/filters.ts. this also allows combining 
a search text (title expression) : 

filters: [{ prop: category, filter: {op:equals, value: category}] ,  { prop: title , filter: {op:contains, value: searchText }] , operation : 'and'

this may look weird right now but pretty much all views can be defined that way and it takes only a few tweaks to transform this expressions to agoila searches.

g

**Comment by tx4x** [comment]
so the filter key 'prop' equals to a property key in the retrieved posts, there is still some tuning needed in the data (and mocks)

**Comment by BenGamma** [comment]
Ok, still seems a bit abstract to me but I'm sure it would be clarify with some code to look at.

To precise about the list sorting, there will be 3 type of sorting :
* Latest
* Most comments
* Most useful

**Comment by tx4x** [comment]
sure, sorting is handled with the grid library in place which only needs slight extra helpers to work.
about the first filter expressions, for instance one which takes selected tags, selected categories, search term into account : i will post here something tomorrow but more or less here is one example which filters the posts by a time threshold and selected tags : https://github.com/OneArmyWorld/onearmy/blob/master/src/pages/Discussions/common/filters.ts#L238
this can be applied to all modules which has lists and search criterias.

**Comment by BenGamma** [comment]
Closing for now, will reopen when needed.
