### ISSUE TITLE
Module - Tags and Filters

### ISSUE THREAD

**Issue by mattia-io** [OneArmyWorld/onearmy#216]

**Comment by mattia-io** [comment]
**Updated 14-01-19 (Mattia)**

**Overview:**
The filter bar is used across the community site to allow users to filter content on the following pages: How-To, Discussions, Events and Maps. 

The filter bar includes the Project selection dropdown, the category and tag dropdown. It should also include search. 

**Latest design resources:**
Prototype
https://sketch.cloud/s/KnZgA/m1O53gL/play

**Originals + Screens**
(coming soon)

**Epics:**
https://docs.google.com/spreadsheets/d/1pkLRKCbQiJOtQwWEhVNgSTvDWf5SnVAz10vMo4k-LNg/edit#gid=0

Any questions post in the comments

**Comment by BenGamma** [comment]
This is on hold for now. Will reopen if appropriate in a close futur.
