### ISSUE TITLE
register on open collective

### ISSUE THREAD

**Issue by BenGamma** [OneArmyWorld/onearmy#223]
A lot of the main projects in the javascript/opensource community are registered on https://opencollective.com/.
We could have a deeper look into it when the plateform will be more advanced.

**Comment by chrismclarke** [comment]
I really like the look of this! But what will we do with all that money? 💸 💸 💸

**Comment by mattia-io** [comment]
great

**Comment by chrismclarke** [comment]
https://opencollective.com/faq/collectives

Basically anybody trying to do things not-for-profit, in an open and transparent way. 
Only downside is their 5% commission (on top of payment processing fees).

**Comment by mattia-io** [comment]
Well fair enough.. they probably have costs :)
Sounds like a powerful tool
@charleenfei is this something similar to what you're working on?

**Comment by charleenfei** [comment]
the idea behind it is the same but the implementation is really different. the hosting infra behind open collective still means all the data is passing through your central DB/server, so is open to manipulation.

**Comment by mattia-io** [comment]
Ohh.. Can you link us up to your project once again?

**Comment by BenGamma** [comment]
Thanks for the discussion, we'll probably look into that kind of plateform in the futur. Too early to know  how we could register on it.
I'm closing for house-keeping reasons.
