### ISSUE TITLE
Best way to track views on post

### ISSUE THREAD

**Issue by BenGamma** [OneArmyWorld/onearmy#232]
We'll need a view counter of each post on the discussion section.
What is best way to achieve this ?
- each time a post page is requested we check the IP adress, if it is unique IP then we increment the `viewCount` value ? That would require to save all IP adress from post page display, may be a lot of data.
- Maybe use a session variable in the cookies ?

**Comment by chupakabra** [comment]
Think using cookies is a better option (if we don't care about views of anonymous users) as IP address doesn't seem unique and representative enough (the same user may view it from different locations or few users may use the same IP address or user may use Tor, etc.) and s you said we will have to store a lot of data.

Found some package which could be useful: https://www.npmjs.com/package/react-count, but didn't figure if it distinguishes users.

Anyway, I'm going to spend some time to try it. 
cc @mattia-io

**Comment by mattia-io** [comment]
@chupakabra brilliant. Keep us updated on this :)

**Comment by BenGamma** [comment]
@chupakabra If at some point you need to access the database, just DM on slack and I'll open access for you :v:

**Comment by chrismclarke** [comment]
If you're thinking of cookies then I'm guessing google analytics would save a lot of time (will need GDPR compliance). 

Personally I would want us to collect only the minimal amount of data that we actually need (I think lots of people in our community are quite opposed to big-data culture), so before going too far it might be good to try define what that is. I'm guessing @mattia-io might have some thoughts on this too.

The other option is to write directly to the database, either via a cloud function or client-side. This doesn't scale quite so well as the same document typically only likes 1-write per second or so, but there are ways around it if we thought there would be need.

A couple links that might be of use:
https://medium.com/google-cloud/tracking-site-visits-on-react-app-hosted-in-google-cloud-using-google-analytics-f49c2411d398
https://firebase.google.com/docs/firestore/solutions/counters
https://tonyxu.io/posts/2018/use-firebase-cloud-function-to-count-website-visitors/

**Comment by chupakabra** [comment]
I struggled a bit with `react-count` applying and tried to set up google analytics tools, but unsuccessfully for both.

-  for `react-count` there was some troubles with `OnlineCount` tag
-  for google analytics I tried different manipulations and debug tool showed that everything seems is fine, but no data neither users nor some events in Analytics overview.

And then was 'wait a minute...', just figured that we don't have any authentication system and don't store any session keys, do we?

**Comment by mattia-io** [comment]
Hey, is this solely concerning the viewCount on pages or is it a larger question on whether we need analytics or not? In what other instances we'll have to track our users?

**Comment by chrismclarke** [comment]
It started as a question on view counts. If we implement a simple database counter mechanism (e.g. each time someone opens a post it adds one) it stays a question on view counts. If we decide we want 'unique views' or tracking by some sort of cookies mechanism as given by one of the suggestions it becomes a more general question.

**Comment by chupakabra** [comment]
My mistake, but I figured later that we don't have any authentication for now, do we? So it won't be possible to distinguish views per user using cookies for now if so.  Tried `react-count` package, but it got some parsing error in `OnlineCount` tag (guess it's related to what I mentioned)

Also, didn't find any model for posts, do we have it all in our db?

Tried to apply GA, seems works fine, though had some issues in Firefox (apparently it was blocked by uBlock)

**Comment by chrismclarke** [comment]
we have firebase auth that can register an anonymous user that we could use for tracking, not fully implemented yet though (WiP)

**Comment by chrismclarke** [comment]
we have firebase auth that can register an anonymous user that we could use for tracking, not fully implemented yet though (WiP)

**Comment by chrismclarke** [comment]
google analytics implemented, closing
