### ISSUE TITLE
subdomain routing and url schemes

### ISSUE THREAD

**Issue by chrismclarke** [OneArmyWorld/onearmy#236]
https://documentation.preciousplastic.com no longer renders the docs page. Router requires reconfig after recent nav refactor.

Just to check @mattia-io, do we still want to display the docs page on the preciousplastic website (address above)?

Would it also be a good point to change over the names to 'how-tos' or similar. If so how would you like the urls to look? e.g. onearmy.world/how-to or /how-tos, and equally how-to.preciousplastic.com, howto.preciousplastic.com etc.

While we're at it (talking navigation), what will the url structure be like for each army? e.g. preciousplastic.onearmy.world/how-tos vs onearmy.world/preciousplastic/how-tos etc?

child of #106

**Comment by mattia-io** [comment]
Hey chris,

Thanks for bringing this up :)
how-to.preciousplastic.com would work for now. 

In regards to the second point what would you suggest? What's best SEO wise? I reckon this could impact the way google would list the site. 

Will also talk with Dave about it

**Comment by mattia-io** [comment]
Cool. 
I wonder as projects will be selected from the Filter bar (@nzchicken working on it). Do we need reload a new page everytime we select a project? Or can projects be just another filter (tag, category..)? SO that we would make our life simpler

Would this be an option? 
oa.world/how-to/#precious-plastic

Just brainstorming here, will bring this up with dave tmw
Ciao!

**Comment by chrismclarke** [comment]
So even though the site is seperated into 'pages' with different urls that's actually mostly for show and it's entirely possible to change a page without reloading. So should still work fine either way (/how-to/precious-plastic, -> /how-to/project-kamp, or running off how-to.oa.world/abc -> how-to.oa.world/xyz etc.). So basically you guys can mostly feel free to start with whatever you think would be most ideal and we can let you know if that works.

**Comment by BenGamma** [comment]
Some news here @mattia-io ?

Last week, I rename all the occurence of tutorial or docs, now the url scheme is the following for the domains :
*onearmy.world/how-to/*
*documentation.preciousplastic.com/how-to/*

Personnaly, I like the selection of the project depending on the url parameters e.g /how-to*?p=preciousplastic* and we will probably add the tags as parameters too, like  /how-to?p=preciousplastic*&tags=material,hdpe*

**Comment by mattia-io** [comment]
Hey chap, 

Just had a chat with Dave. Few favourite options from us, even though you should keep in mind that for us doesn't really matter that much as long as it works smooth and the url is understandable (clean). So the easier / most efficient for you guys to get the job done. 

1. https://community.onearmy.world/ should be our community site home page. We would also like this to be the only one subdomain on the platform for now (of course excluding the dev site)
2. Our preferred option would be page/project/title or tag:

https://community.onearmy.world/how-to/preciousplastic
https://community.onearmy.world/discussion/preciousplastic+HDPE+PRODUCT
https://community.onearmy.world/discussion/all

Does that clear? 
Let me know if you need anything more from us on this

**Comment by chrismclarke** [comment]
Makes sense to me, will try get it implemented shortly

**Comment by BenGamma** [comment]
To summarize the subdomain routing for now :
* https://community.onearmy.world/ wil be used as main url for the onearmy app.
* https://onearmy.world/ will be our landing page, explaining what is onearmy.
* We'll have https://dev.onearmy.world/ that reflects the `master` branch.
* We'll have https://beta.onearmy.world/ that reflects the `production` branch.
* We stop using https://documentation.preciousplastic.com which is no longer relevant and complicated to maintain over time.
* The `/discussion/tags` path scheme is on hold for now.
