### ISSUE TITLE
New contributor call to arms

### ISSUE THREAD

**Issue by chrismclarke** [OneArmyWorld/onearmy#24]
Want to advertise fact that we are actively developing new platform and open to contributions
depends on #6

**Comment by chrismclarke** [comment]
also need to follow-up with latest slack additions (Thomas and glauberramos)

**Comment by mattia-io** [comment]
I can throw it in to the communication team which is currently responsible for writing posts on DH. Maybe they have a cool way of writing about it being specific but without giving away too much.

**Comment by chrismclarke** [comment]
More help would definitely be appreciated, I’m likely to drag my feet a little on this one until more of the dev priorities are met but keen to contribute what I can

**Comment by chrismclarke** [comment]
pushing this into the backlog for the next week or so to see how much the new remote devs are able to contribute and get feedback on the current induction system (it's a bit of work but hopefully gets people up and running fairly smoothly)

**Comment by chrismclarke** [comment]
lots done and now being taken over by mattia so closing
