### ISSUE TITLE
Make inline links, links

### ISSUE THREAD

**Issue by mattia-io** [OneArmyWorld/onearmy#243]
Currently links within the text are not clickable links. Would be nice if they could be clickable. Not sure if this will be solved by #211

![Screenshot_2019-01-30_at_08_53_35.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5beadf2e66e72100136491d9/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf60da1cd6416763e7a549c2a64bab3708017283e5c5a5cb053181d1ba6acda6fb4bc2e75d80d58be8064597c946f14adbb821fb950bf218e4c87b7ae965e82b96371b8d6d6056b5c17129bfe5a3fa19c4fc050f54fe84e5ca0103071ab.jpg)

child of #3

**Comment by harrier91** [comment]
@mattia-io I can do it

**Comment by mattia-io** [comment]
Yep, go ahead. All yours 🙌

**Comment by BenGamma** [comment]
implemented with #248 closing.
