### ISSUE TITLE
Filterbar backend

### ISSUE THREAD

**Issue by mattia-io** [OneArmyWorld/onearmy#245]
Based on filterBar frontend (#244 ) create the backend system to get the relevant tags.
child of #216

**Comment by BenGamma** [comment]
Hey there !
A first implementation of tags system as been done by @chrismclarke and is available in `src/pages/common/Tags`
Can we base the new version of the tag system on it ?
This is a pretty important feature and I think it would be nice to have it done before the end of february. I'm up to work on it but I'll need some help for the backend part of it.

**Comment by chrismclarke** [comment]
Happy to help, perhaps we can try do this when I'm around Eindhoven next week?

**Comment by mattia-io** [comment]
This might need a little extra explanation.. quite a complex module with repercussion across different pages. What's the best way to explain it out in full @tx4x ?

**Comment by tx4x** [comment]
@mattia-io : i have to first investigate [ `Agolia search` ](#328) first and also play with a next iteration of the  filter system for the discussion list. the whole thing is indeed a little big but I expect first usable results next Monday.

**Comment by mattia-io** [comment]
Brilliant, let's talk then

**Comment by tx4x** [comment]
hey guys, no idea what to do in the backend yet. I'd prefer to wait that also the post's type/category is implemented first.

**Comment by chrismclarke** [comment]
Cool, I didn't manage to find any time this weekend but will put this up my priority list perhaps for one evening this week.

**Comment by BenGamma** [comment]
Closing for now, will repopen when needed.
