### ISSUE TITLE
Q&A post

### ISSUE THREAD

**Issue by mattia-io** [OneArmyWorld/onearmy#253]
**Updated 08-02-19 (Mattia)**

**Overview:**
Users can post questions to the community and get answers from other users. Any users can post their answers to the question and reply to answers. The author of the question can select one correct answer.   

Users should be able to "useful" and save the Q&A and should also be able to "useful" answers.

![v9 Discussions_question.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5beadf2e66e72100136491d9/125516c66e82c728ace21e0d46fecdda078b90aa9afaac4aab53e3ab385322603d0dac2532c9a138ad4d71040c1b5ca6535d0d15afaad822a0be6e228f5d08edd16b0e71c73812aeb99003ad43eb7edf10d8eff6df0ed2e22f24ef818e4a3a17031b8ffd5430a59f4dda15.png)

**Latest design resources:**

**Originals + Screens**
https://drive.google.com/drive/u/0/folders/1beL2iYCJKvFrxK8BvtX51Kc7HcXWL31O

**Epics:**
https://docs.google.com/spreadsheets/d/1pkLRKCbQiJOtQwWEhVNgSTvDWf5SnVAz10vMo4k-LNg/edit#gid=0

Any questions post in the comments

child of #213

**Comment by BenGamma** [comment]
closing cause reorganizing in #409
