### ISSUE TITLE
Discussion post

### ISSUE THREAD

**Issue by mattia-io** [OneArmyWorld/onearmy#254]
**Updated 08-02-19 (Mattia)**

**Overview:**
Users can write a post to discuss their process, ideas, doubt or just get some feedback. Other users can reply to the post and reply to replies. 

Users should be able to "useful" and save the post and should also be able to "useful" replies.

**Latest design resources:**

**Originals + Screens**
https://drive.google.com/drive/u/0/folders/1sFiV0PT0_UPIefEGWB0Ev0LQbPEZk5p0

**Epics:**
https://docs.google.com/spreadsheets/d/1pkLRKCbQiJOtQwWEhVNgSTvDWf5SnVAz10vMo4k-LNg/edit#gid=0

Any questions post in the comments

child of #213

**Comment by BenGamma** [comment]
Closing for now, will repopen if needed.
