### ISSUE TITLE
Best data structure for Q&A post

### ISSUE THREAD

**Issue by BenGamma** [OneArmyWorld/onearmy#255]
Using the mockups described in #253 we need to describe in a data structure what we’ll display on the screen.
The main entities to me here are :
* the post containing the question and the answers
* question post with description infos & possible chosen answer
* answers with autor, description and possible replies

In the past I've used https://next.json-generator.com/ to generate random datas, can be useful here also.
When ready, mocks datas will lives in `src/mocks/qapost.mocks.ts`

These data will help the frontend developer to start building the interface.
child of #213

**Comment by chrismclarke** [comment]
My main advice would be to try to avoid too much nesting. I think likely we would want to use a single collection for all questions, and then a subcollection for all responses within a collection, i.e.

`/qanda/[generated question id]`
`/qanda/[generated question id]/answers/[generated answer id]`

within a question document we would have whatever standard fields desired for storing information (title, description/content etc.), I would suggest avoiding fancy slugs and just use the generated id, and we might want some extra meta fields to track the usual `_created` , `_modified` alongside project, tags, isOpen (or similar), and probably totalResponses which would need to be populated using cloud functions on the server.

I would expect the answer document to have a similar format, although it woudn't be necessary to track any of the information from the parent question as it will sit within the parent question subcollection. I can't remember what mechanism we had decided for ranking responses, so possibly would need a tracker for upvotes or whether chosen as featured response. To handle nested responses we would probably want to have some sort of 'responseTo' field if it is marked as a nested response, and then some recursive magic client-side to put all in the correct order and nesting.

The more I write this the more I realise keeping that things simple will actually be pretty complex! I think most likely it will undergo a couple different iterations, so maybe best to just start with anything and take it from there.

**Comment by chrismclarke** [comment]
starting work...

**Comment by chrismclarke** [comment]
model updated and mock generated, includes nested comments. Likely will need slight modification in the future  for marking comments as useful/starred/upvotes etc depending on system we want. Code in the discussions branch
