### ISSUE TITLE
create Answer component

### ISSUE THREAD

**Issue by BenGamma** [OneArmyWorld/onearmy#258]
Child of #213
Child of #256 
Create the Answer component that will display an answer like in this mockup (outline in red):
![discussions_answer](https://user-images.githubusercontent.com/4993215/52488899-32a70580-2bc1-11e9-85c0-405251736546.png)

**Comment by darrylAlexander** [comment]
After speaking with @mattia-io I would like to have a go at making this component.

**Comment by mattia-io** [comment]
Brilliant ⚡️

**Comment by chrismclarke** [comment]
Not sure if this is moving forward, would be good if it could. I've just pushed a very barebones template to the `module/discussions` branch so that @sri can work on the response mechanism (#260)
