### ISSUE TITLE
Create the answers voting (usefull btn) mechanism

### ISSUE THREAD

**Issue by BenGamma** [OneArmyWorld/onearmy#259]
For each answer, users can vote if the answer was usefull to them by clicking the "usefull“ button.
Outlined here :
 
![discussions_usefullcounter](https://user-images.githubusercontent.com/4993215/52490029-1ce70f80-2bc4-11e9-9a2a-f33d827b8f99.png)

Needs #254 
Can be related to #232

**Comment by grahamlyons** [comment]
Should this be closed as the dependency, #254, has been closed?

**Comment by BenGamma** [comment]
Yes, closing
