### ISSUE TITLE
Create the reply to answer mechanism

### ISSUE THREAD

**Issue by BenGamma** [OneArmyWorld/onearmy#260]
child of #213
child of #258 
On a thread, when you click on the reply button from an answer, it open the editor to reply to the selected answer. On save the reply is saved to the database and UI updated with the reply.
Mockups :

![discussions_reply](https://user-images.githubusercontent.com/4993215/52490957-40ab5500-2bc6-11e9-9962-f40b4f8898c4.png)

**Comment by mattia-io** [comment]
@sri is working on this 🙌

**Comment by chrismclarke** [comment]
So the database side of this is actually a bit complex. Would suggest @sri reaches out if working on it. I've added a discussion view page which can work as a base for this (currently just rendering a single list of replies without nesting, but can be built on)

**Comment by chrismclarke** [comment]
quick discussion had with sri on slack, hopefully good to move forward on this

**Comment by chrismclarke** [comment]
> @sri is working on this 🙌

Apologies to the real @sri , the Sri in our repo should be referred to as @vatsan28
(@mattia-io )

**Comment by mattia-io** [comment]
Oh 💩

**Comment by BenGamma** [comment]
I think this was implemented with the creation of the backend for post by tx4x, right ? @chrismclarke 

Did you start working on it @vatsan28 ?

**Comment by chrismclarke** [comment]
I created a placeholder to get started with so perhaps let us know if you have got stuck @vatsan28 , or if you have been unable to find time then what your current estimated timeline is

**Comment by BenGamma** [comment]
Closing for now, will repopen when needed.
