### ISSUE TITLE
Add dev site notice

### ISSUE THREAD

**Issue by chrismclarke** [OneArmyWorld/onearmy#272]
would probably be good to have a small message somewhere stating that this is the dev site, and any data shared is openly available. This wouldn't be shown on live site, but the code might be adapted for cookie policy or any other requirements

**Comment by BenGamma** [comment]
#272 added a little icon on top of the page that lived in `src/components/Dev/DevNotice.tsx` based on the isDebug node variable.
What would be nice to have is on hover a little tooltip with this indication :
"This is the dev site and all datas posted here can be public"

**Comment by mattia-io** [comment]
@sanjuskm05 is now working on this ⚡️

**Comment by sanjuskm05** [comment]
Submitted the pull request. Whenever possible, please review and merge it

**Comment by chrismclarke** [comment]
reviewed, minor changes requested, please update the PR when complete. Thanks
