### ISSUE TITLE
Remove mobx dev tools from production build

### ISSUE THREAD

**Issue by chrismclarke** [OneArmyWorld/onearmy#276]
currently shows timeline options in top-right corner even for users without mobx extensions installed. Should find a way to remove.

See https://onearmy.world  or image of navbar below for example

![image](https://user-images.githubusercontent.com/10515065/52945021-13526a00-3371-11e9-95fa-1d60b0450951.png)

**Comment by tx4x** [comment]
i found only one way to figure that the extension is installed:  check that window.__MOBX_DEVTOOLS_GLOBAL_HOOK__ isn't empty. i can add a function 'hasMobxDevTools' in src/config for that.

**Comment by tx4x** [comment]
damn, i think there will be some conflicts, i have 2 PRs requiring a new function in src/config 'isDebug'. adding now the new one 'hasMobXDevTools' should wait for the others to be merged.

**Comment by chrismclarke** [comment]
realised issue (pretty stupid of me), in the `src/pages/index` the `<DevTools />` element is passed. Can just add a condition to check the site variant. Will commit now.
