### ISSUE TITLE
Implement Algolia search

### ISSUE THREAD

**Issue by chrismclarke** [OneArmyWorld/onearmy#328]
Following discussion #210 the suggestion is to try out Algolia search. It would make sense to first try with one of the database endpoints like howTos (/documentation), populating data to algolia through cloud functions on database updates and implementing the search API.

If anyone wants to take this on I'd be happy to set up required API tokens etc for Algolia. 

Code sample here:

https://firebase.google.com/docs/firestore/solutions/search

(note to self/future ref, free community plan fine for dev but as we move to production may want to explore openSource project discount)

**Comment by chrismclarke** [comment]
Dev server keys created and included in src/config. Production keys will be generated at a later date (requires alternate email account, to be created), and passed through environment to backend and frontend code.

Algolia dev account login: hello@onearmy.world, pw: z7j28DsPcXRT9cr

**Comment by tx4x** [comment]
cool, i will have a look next week! From what i see is that the proposed filter system in my PR needs only a few tweaks to satisfy their search/filter system.

**Comment by tx4x** [comment]
i don't mind the tool selection but it looks like Agolia is pretty pricey over ElasticSearch, searching the net, : 
see https://stackshare.io/stackups/algolia-vs-elasticsearch or similar comparisons.

**Comment by chrismclarke** [comment]
The problem with elasticsearch is it requires a cluster of host machines, so even with a minimal server setup that'll probably run at around $50 per month. Then take into account that our usage might fit entirely within their free tier, particularly as their free open source plan includes 100k records and 200k operations ($70 equiv value) which we can apply for.

It's hard to know exactly what the usage will be, I haven't even thought about running numbers but I think it makes sense to start with and see

**Comment by tx4x** [comment]
Scheduled for Thursday

**Comment by tx4x** [comment]
hi,
so after checking, i can't get my head around firebase in conjunction with mobx and now building agolia search in top. for that I seem to miss the bigger picture, more documentation or just learning the whole stack.

**Comment by chrismclarke** [comment]
Yeah, I think at some point I really need to build a systems/architecture diagram because I can see how it would be confusing. It doesn't help that firebase is a term for a family of different products (so not just the database used), and sits on both front and back ends in different formats. I'll add an issue to try and address this at some point in the future (although will likely be a couple weeks until I have the time)

**Comment by chrismclarke** [comment]
Note, current account will expire if requests not made shortly (no biggie as can just create a new one and change ci variables, but if sending a single demo request is easy probably worth doing)

**Comment by tx4x** [comment]
I thought Agolia is out due to policy regarding foreign libs and services ? Anyway, I am just wondering. I'd prefer something which works offline, more simple, closer to Lucene etc.. Keep in mind the filter system in discussions needs to be mapped to indexer expressions ( similar to SQL syntax )

**Comment by BenGamma** [comment]
Closing for now, will repopen when needed.
