### ISSUE TITLE
Test production deploy

### ISSUE THREAD

**Issue by chrismclarke** [OneArmyWorld/onearmy#336]
There's been quite a few config changes and whilst everything seems to be working fine on dev it will be important to check the right environment variables are passed to production also.

Let me know when we're next planning on a production pull and I'll make sure to be on hand to test and rollback deploy site if not correct

**Comment by BenGamma** [comment]
I think we can plan to push in production when discussion module will be ready for some user testing. Somewere during the first week of march sounds like doable to me

**Comment by chrismclarke** [comment]
Sounds good to me

**Comment by chrismclarke** [comment]
assume will push in line with new module versioning system, closing here
