### ISSUE TITLE
Does tinymce strip html?

### ISSUE THREAD

**Issue by chrismclarke** [OneArmyWorld/onearmy#345]
@tx4x
I'm adding a small component that renders the content saved from the tinymce editor. It is possible to render directly however this could be a security risk if injected with xss.

If fine, can just use the `dangerouslySetInnerHTML` prop (sounds scary but fine if content trusted). Otherwise there's 3rd party libs that can check/strip e.g. https://github.com/cure53/DOMPurify.

Any advice?

**Comment by tx4x** [comment]
no, and it shouldn't because otherwise you actually don't need a WYSIWYG editor in the first place though.
if it would, all formatting and user images, layout is gone. 

there are enough libs however which let you strip certain tags (better at save time, no?), yes and i think this is what should be done. let me check, i've done this a few times :-)

**Comment by tx4x** [comment]
don't forget there is also a couple of plugins coming for tinymce: mention, media embed and internal links.

**Comment by tx4x** [comment]
here is a library which enables white-listing of tags : https://www.npmjs.com/package/striptags

**Comment by chrismclarke** [comment]
Apologies, I didn't mean all tags, just things that could be used for XSS attacks (i.e. scripts, javascript calls, certain iFrames etc.). The repo suggests most but not all common attacks are stripped by default:
https://www.tiny.cloud/docs/advanced/security/

It's not quite as simple as stripping all tags as you can also do things like injecting a function into the onerror function of an `<img />` tag. Although we might want to consider a set of whitelisted tags and the package above if we want to strongly enforce the options given to a user in the editor (personally no strong opinions on this, although probably leaning more to the "let people do what they want if they're really that determined" side.

In terms of the custom plugins we want to build we probably don't want these to pass in a script tags, as the browser can only render dynamically injected custom tags (e.g. `<mention userId='abc' />` ) if we built the mention component as a separate webcomponent (not opposed to, just a little bit more work and slight different design pattern to rest of site). Instead we would likely need to have a script that parses the received html and uses regex to pick up on whatever templating system we decide on (e.g. `[[mention:userId]]` ,`[[@userId]]` etc.), using the main `render()` method to call our custom elements where required.

**Comment by chrismclarke** [comment]
Looking online it sounds like most xss vulnerabilities are regularly updated in TinyMCE, however for added security suggest that we try and add a html sanitizer (like DOMpurify) to the editor. Does this sound reasonable? Would it be much work?

**Comment by tx4x** [comment]
yep, sounds all good to me.

some time ago I used in top of sanitizing a white list for tags, with another list of white listed attributes per tag. 

let me finish (almost) the discussion list PR and head over to that stuff. the content parser itself is pretty trivial indeed (yup, as simple string template substitution function) , I am not quite sure yet how to do it but I am sure that this can be finished end of next week. I'd suggest to make baby steps and slice it to small PRs, possibly this goes better via slack. 

I am also not sure about the scope, i think this is better done server-side, for savePost|Comment, postDetail; at least that's what i'd do in regard of hardening this.

**Comment by tx4x** [comment]
i just checked, In addition I also signed (HMAC) the whole payload with a security token but no idea what to use or do nowadays, I only figured that JWT does a good job :-)

**Comment by chrismclarke** [comment]
I think nothing is urgent priority, just good to keep on the agenda for whenever the time fits. 
We won't need JWTs just yet as we can apply rules on top of firestore which uses their own internal token system (but would want to if we wanted to decouple from firestore which again is something that has been talked about as a long term option).

Cool, my discussions back/front overhaul has now been comitted but probably easiest if you create the PR to master or discussions-backend (at this point probably master easier) and I'll handle resolving conflicts to reintegrate (assuming your code will be easier to follow than mine!).

**Comment by tx4x** [comment]
cool, deal ! 
now let's f** off for a sunny nice sunday :-)

**Comment by tx4x** [comment]
closing this in favor of #354 and https://github.com/OneArmyWorld/onearmy/pull/365
