### ISSUE TITLE
Tidy discussions module naming conventions

### ISSUE THREAD

**Issue by chrismclarke** [OneArmyWorld/onearmy#346]
Currently we have a mix of the top level discussion/question/post and then child comment/response.

Should decide on what works best for current module and make consistent (can always change later).

**Comment by BenGamma** [comment]
I like the term Post because it can describe clearly different type (question/discussions) and avoid misunderstanding

**Comment by chrismclarke** [comment]
I think I'm agreed, will try to change things over next time I'm working on it

**Comment by chrismclarke** [comment]
When doing so there's also some extra interfaces from post lists that should be merged in (see #358)

**Comment by chrismclarke** [comment]
Might be worth doing a bit later when there are fewer people working on the module

**Comment by chrismclarke** [comment]
As lots of future changes likely for discussions closing this issue here and can revisit conventions when identified for future sprint
