### ISSUE TITLE
Link logged in user to database operations

### ISSUE THREAD

**Issue by chrismclarke** [OneArmyWorld/onearmy#347]
placeholder for 'createdBy' in discussions generated. Needs implementation but first requires login fix

**Comment by mattia-io** [comment]
@suvya is on this

**Comment by suvya** [comment]
@chrismclarke Can you please provide more details on this enhancement and also I read that it requires a login fix, Please help me understand if I have to address it first?

**Comment by chrismclarke** [comment]
Hi @suvya, this isn't a good issue to pick up and hence why it has not been marked with the `good first issue` or `help wanted` tags. It is minor and I plan to do it myself. It is simply to add to the existing database functions to populate the user id on creation of new database objects (basically one line of code), so really not worth worrying too much about

**Comment by chrismclarke** [comment]
fixed, will merge with `user-profiles` module
