### ISSUE TITLE
Create user avatar component

### ISSUE THREAD

**Issue by chrismclarke** [OneArmyWorld/onearmy#351]
Want a simple component that will:
1) Take a userid (email), and look up their avatar from the database
2) Render as a small image

Note (to self), the user avatar might need to be stored in another database location to rest of profile depending on security rules (assume only users will have read/write access to their own doc, although could perhaps try figure out a way to give read permission to certain fields)

**Comment by kopecms** [comment]
About this read/write access to only own doc, don't we want to allow ready other users profile data like display name country (email perhaps)?

**Comment by chrismclarke** [comment]
I think what most of this comes down to is whether users will have any private information saved. At this point I'm assuming mostly no, all the information saved in the user doc is what they choose to put into their public profile, however both the id of the doc and a field within contain the email address the user signed up with which they probably don't want to share.

So either we remove reliance on emails, keep username keys and remove from field, or we have all of the user docs readable only by the user and add a separate api endpoint on the server that can get things like avatars for a given user.

**Comment by chrismclarke** [comment]
The reason any of this matters is because documents retrieved from the database are cached offline to local storage (indexedDB), so a user could easily use any of that data even if not explicitly exposed within the interface, e.g.
![image](https://user-images.githubusercontent.com/10515065/53571833-bc634680-3b61-11e9-99d7-4022ec3447d4.png)

**Comment by kopecms** [comment]
Maybe deleting email address from users doc is not that bad idea (we can add private data doc later when needed). Displaying discussion or any other entity anyway require downloading users public profile. So maybe I will replace email with id generated when creating Authentication profile? And add avatar and other public data to /users doc?

**Comment by chrismclarke** [comment]
I think that probably makes the most sense at this point. I'm guessing we could also save the user doc using that same id.

**Comment by BenGamma** [comment]
created new related issue #399 for using user id instead of email since Avatar component is now created and merge
