### ISSUE TITLE
Add user signup functions to user store

### ISSUE THREAD

**Issue by chrismclarke** [OneArmyWorld/onearmy#356]
`stores/user.store` currently has a couple functions for logging in users, and there is a separate set of functions to handle user migration in `utils/user-migration`. Need extra functionality in user store to:

1) register a user with the input username and password via firebase auth
2) create a new database entry at `Users/${user.email}` which contains the signup info fields (if registration successful)

Could add consideration as to how to handle situation where one step success and other step fail

child of #8

**Comment by kopecms** [comment]
@chrismclarke I will be happy to continue on this issue ; )

**Comment by chrismclarke** [comment]
closed with #357
