### ISSUE TITLE
Add backend function to populate total discussion responses when comments added and deleted

### ISSUE THREAD

**Issue by chrismclarke** [OneArmyWorld/onearmy#359]
child of #213
Currently when a user creates a post it contains a `resonses:` field which will track the number of responses. 

When responses are created they are added to a subcollection (e.g. `discussions/${discussion._id}/comments/${comment._id}`), and so the original document has no way of knowing how many responses there are without running a query to get them all (which is inefficient/expensive, as the full subcollection documents aren't required on a list view page).

So the usual solution is to add a cloud function, which will respond to a trigger when the subcollection doc is created/deleted to increment or decrement the parent doc field

some examples which might help get the idea:
https://angularfirebase.com/lessons/firestore-cloud-functions-data-aggregation/
https://firebase.google.com/docs/firestore/solutions/aggregation
https://firebase.google.com/docs/firestore/solutions/counters
(although definitely won't need full distribution counter, single counter will be fine)

**Comment by chupakabra** [comment]
I think I will focus on that this week
@chrismclarke, @mattia-io

**Comment by mattia-io** [comment]
NIce one @chupakabra 🙌
