### ISSUE TITLE
Fix cover-image display on how-to

### ISSUE THREAD

**Issue by BenGamma** [OneArmyWorld/onearmy#361]
The how-to cover image is stretch when displaying the how-to page, you can see an example here : https://onearmy.world/docs/Create-a-raincoat-from-plastic-foils
The wanted behavior will be that the image keep the correct aspect ratio.

**Comment by jameswakefield** [comment]
@mattia-io: what is the desired behaviour for the presentation of the cover image? Does it need to be a certain width/height or can it be displayed at it's original dimensions? The 'styled-component' `<CoverImg>`:https://github.com/OneArmyWorld/onearmy/blob/d914803e8b92121d8fb237442a8047958caa4996/src/pages/Howto/Content/Howto/HowtoDescription/elements.js#L31-L35 has styling that makes the `<img />` element it fill the width of it's parent. The parent is a container with a % width that can vary based on the width of the screen. However the image height is restricted to 360px: https://github.com/OneArmyWorld/onearmy/blob/d914803e8b92121d8fb237442a8047958caa4996/src/pages/Howto/Content/Howto/HowtoDescription/elements.js#L32 which was added by @chrismclarke here: https://github.com/OneArmyWorld/onearmy/commit/9e32ee200f3090c5081fa8abf7ed73aeeb2aeafd

**Comment by jameswakefield** [comment]
Proposed fix from @flakessp fix in PR: https://github.com/OneArmyWorld/onearmy/pull/372

**Comment by BenGamma** [comment]
Closed with #372
Thanks guys !
