### ISSUE TITLE
Nest comment replies

### ISSUE THREAD

**Issue by chrismclarke** [OneArmyWorld/onearmy#363]
currently all comments are stored in flat list, but do have a `respondsTo` key which indicates parent-child relationship for nested comments.

Ideally want to recursively build the full comments tree and then render nested. The logic wouldn't be too tricky, alternatively could just use something like https://www.npmjs.com/package/flat-to-nested

child of #213

**Comment by tx4x** [comment]
how you want to limit intents, not sure what facebook has, but i guess there is one. common sense tells me 4 intents are pretty on the edge to looking messy

i thought earlier to use the new grid's tree renderer (cant wait to add keyboard) but as always this depends on the store facilities, does the mobx thing supports on a nested tree and how does notifications look like then, API vise though

boah, miles to go, i will only dig around this week: filters, full-text search and front-end and backend is huge thing, considering the mistakes one can do :-)

**Comment by tx4x** [comment]
@chrismclarke ,
I will be back as soon I can, max. Monday. I have to sort our unexpected and harsh problems with the bazaar.

**Comment by chrismclarke** [comment]
What do you mean by intents here? As in what sharing to other media platforms might look like? If so I think that discussion belongs in a different thread, this issue should be a fairly simple one, take an array of data which has a bunch of parent/child key relationships, and create the correct nested tree structure for the data (like the demo in the npm package listed)

Definitely a long way to go so all the support is much appreciated! I'm now travelling for the next 6 weeks but will try to keep on top of what bits I can

**Comment by tx4x** [comment]
right,
i though this was a about displaying the reply tree (needs intends)

**Comment by chrismclarke** [comment]
it is, but I'm not sure what you mean about intends/intents... not a term I'm familiar with given the context so please elaborate/post link/or just ignore me :D

**Comment by tx4x** [comment]
it's written indent, not intent, sorry :p

**Comment by tx4x** [comment]
@chrismclarke , so somebody is there to review/merge PRs ? i have some stuff for Monday: filterbar, and with some luck agolia search

**Comment by chrismclarke** [comment]
Oh, that makes a lot more sense. Yes I see what you mean, we can't keep infinitely nesting... not really sure how other sites handle that sort of thing

**Comment by chrismclarke** [comment]
I'll be checking PRs when I can, generally benji also reviews on Tuesdays, but typically more focused on the frontend stuff

**Comment by tx4x** [comment]
Good morning, maybe it's better that someone from the ux department takes a look at it first .

**Comment by BenGamma** [comment]
Hey mornin' @tx4x !
The design team is currently working on that and will be answered soon with some more precise mockups. For now you can consider that there is one indent on the first reply to a comment and then replies stays on the same indent level.
The data structure would look like so :
* a discussions_collection
* that contain a comments_collection
* each comment in the comments_collection can contain his own comments_collection.

Tell me if it doesn't sound clear 🙃

**Comment by tx4x** [comment]
crystal clear! thanx for the heads up
g

**Comment by BenGamma** [comment]
Closing as it's part of discussion module
