### ISSUE TITLE
Authenticated user not shown as logged in

### ISSUE THREAD

**Issue by chrismclarke** [OneArmyWorld/onearmy#370]
child of #8
I log in successfully however the sign in modal doesn't dismiss and I can still click the button to log in. I'm assuming this is because my email isn't verified? Would be good to have a clearer indication that is the case and mechanism to resend verification email.

![image](https://user-images.githubusercontent.com/10515065/53599540-509fce80-3b9f-11e9-8d42-daed8b2e1816.png)

(screenshot, successful login/auth user state change but modal and log in button still present)

**Comment by kopecms** [comment]
it's a feature ;p I have added link below the form for password (it will show up when email is not verified) #371. I want to work during weekend on this a little more and hopefully close all related to registration/confirmation issues (probably besides styling)
