### ISSUE TITLE
App-size getting too big

### ISSUE THREAD

**Issue by tx4x** [OneArmyWorld/onearmy#378]
not sure what the limit should be, but the build in master ends in 1.7 MB where 700Kb is for JS files alone. 
i understand that certain parts will be removed, like material ui..I just wanted to bump this here as notice :-)

**Comment by tx4x** [comment]
just as reference, I've managed to develop a full and pretty complex IDE with around 2MB in app size some years ago (see https://github.com/tx4x/control-freak/issues/1)

and so from what i see under /discussions should not exceed 250 KB in JS. i know it's a little blunt to make this comparison but lets please take care a little

**Comment by BenGamma** [comment]
the current scan of the package.json point the material-ui icon as a really really bad guy 😈 

https://bundlephobia.com/scan-results?packages=@ephox/sand@2.0.11,@material-ui/core@3.7.1,@material-ui/icons@3.0.2,@sentry/browser@4.6.3,@tinymce/tinymce-react@3.0.1,@types/rebass@3.0.3,@types/styled-components@4.0.0,@types/styled-system@3.2.2,@types/dompurify@0.0.32,bfj@6.1.1,date-fns@1.30.1,dompurify@1.0.10,eslint@5.12.0,eslint-config-react-app@3.0.7,eslint-plugin-flowtype@2.50.1,eslint-plugin-import@2.14.0,eslint-plugin-jsx-a11y@6.1.2,eslint-plugin-react@7.12.4,final-form@4.10.0,final-form-arrays@1.1.0,firebase@5.8.1,fs-extra@7.0.1,google-oauth-jwt@0.2.0,googleapis@37.2.0,identity-obj-proxy@3.0.0,leaflet@1.3.4,md5@2.2.1,mobx@4.9.2,mobx-react@5.4.3,postcss-flexbugs-fixes@4.1.0,postcss-preset-env@6.5.0,postcss-safe-parser@4.0.1,query-string@6.2.0,react@16.8.1,react-app-polyfill@0.2.1,react-dev-utils@7.0.3,react-dom@16.8.1,react-final-form@3.6.6,react-final-form-arrays@1.0.6,react-firebase-file-uploader@2.4.2,react-ga@2.5.7,react-icons@3.2.2,react-image-gallery@0.8.12,react-leaflet@2.1.4,react-linkify@0.2.2,react-router@4.3.1,react-router-dom@4.3.1,rebass@3.0.1,resolve@1.10.0,styled-components@4.1.3,styled-system@4.0.0,typescript@3.3.3,wordpress-hash-node@1.0.0

**Comment by chrismclarke** [comment]
yeah I think we should push to remove all material-ui/icons over the next couple months as the rest of design moves forward

**Comment by chrismclarke** [comment]
Although remember, even if the scan shows a package is large if it's been imported correctly then only small parts of it will be included in the final build (so removing the entire package is unlikely to affect the production bundle size very much at all)... but still, nice to not have multiple competing systems
