### ISSUE TITLE
Discussion post save appear to be broken

### ISSUE THREAD

**Issue by BenGamma** [OneArmyWorld/onearmy#381]
To reproduce :
* try to create a post on http://localhost:3000/discussions/create
* open the console
* click on save button
Then kind of an infinite loop starts, it's a console.log from the `_createNewDiscussion` function in `src/stores/Discussions/discussions.store.tsx`

Then the loops keep going and post is not saved in `discussions` collection. Do you have an idea on what append here @chrismclarke ?

**Comment by BenGamma** [comment]
The saveDiscussion function was call inside herself, wich causes the infinite loop. Fixed with previous commit. It's probably due to a moment of inattention from a previous merging.

The post still doesn't appear in the database thought. I keep it open.

**Comment by tx4x** [comment]
yup, i tried explaining this to @chrismclarke  already, i tried debugging it but as often, that react/mobx magic makes it hell

**Comment by BenGamma** [comment]
Can you point me to the related issue or discussion where you tried to debug ?
This is pretty critical and I would like to try to fix it as quick as possible.

**Comment by tx4x** [comment]
i think it was within the 'TinyMCE editor doesn't clear', but me and him didn't know much about nor what to do.

**Comment by tx4x** [comment]
@BenGamma , @chrismclarke , @davehakkens, @mattia-io : your mod is running mad, please take care that our personal names are removed from the posts. this is illegal and you don't have our authorization to do so because if not you're in serious trouble with me. i don't want to end this in a stupid drama, you've already done enough this way. 

see : https://davehakkens.nl/community/forums/topic/portable-desktop-injection-machine/page/3/ 

we also demand an apology for the removal of our content from the public domain, the lies and accusations are unacceptable.

**Comment by tx4x** [comment]
@BenGamma , @chrismclarke , @davehakkens, @mattia-io : the name are still there. i am waiting

**Comment by tx4x** [comment]
@BenGamma , @chrismclarke , @davehakkens, @mattia-io

**Comment by tx4x** [comment]
@BenGamma , @chrismclarke , @davehakkens, @mattia-io : i understand you have to protect all your lies with even more lies but you're crossing the line when you put others through your dirt machinery (oliver)

anyways, I am on on my way to Eindhoven. will be there in around 30 hours of a shitty drive. I hope you have a good apologize to destroy all our content (again) and a real good explanation what's going on.

**Comment by BenGamma** [comment]
Hey, I don't really understand what's going on here. If you want to recover data it's probably doable but I have no clue on how to do this right now since it's 1am and I don't have any hand on the forum server. I suggest we'll found a solution tomorrow after a good night of sleep.

**Comment by tx4x** [comment]
it's about hillarious lies, about one of our associates, she's been put through the dirt by one of you mods in the most miserably way. we also gave no authorization to use her full name. i don't mind about the loss of $$, time and content (for now) over the last 12 years, created by all the other lies but this one goes too far. 
So reach out Oliver, to remove the name and remove his dirt machinery on our organisation, due to inconvenient questions, allegations. I don't fucking care what time it is, seriously. Your guys fucked up badly.

**Comment by tx4x** [comment]
just to make it clear: we're looking here not just the damages you've created already with the PP docs/kit, this is also now about false accusation against some of us, illegal distribution of private names. so you better make this right ASAP. sorry to say it like this but that's crap at hand there you don't make much friends here, with the court or friends in Eindhoven, but no worry. I am reasonable, just get your sh* right, now please. 
g

**Comment by BenGamma** [comment]
All I know is that we've been colaborating here since a month and yeah you seems reasonnable and a dedicated contributor. The rest I'm not aware of and it seems to take unwanted proportions for everyone. Will see tmrw how to reach this Oliver (that I've never heard about before now) to make the light on this.
That beeing said you may don't but I care about the fucking time and how you talk to people, and understand that you are not making me wanted to help by talking like you do.
Anyway, can you provide a proper email so we can exchange elsewhere than here ? Thanks

**Comment by tx4x** [comment]
baumgart.guenter02@gmail.com 

you guys have to understand that crimes like false allegation public, putting people though the dirt having nothing to do is crossing the line once again too often. we expect from you a complete and public apology in the forum and via email.

your organisation already causes enough damage to others but the behaviour of Oliver goes to far.

**Comment by tx4x** [comment]
after consulting/feedback a lawyer and our mutual user base , in that email we need also an official statement why reference material of our users/clients team-members has been knowingly rendered useless and basically destroyed, without any prior consensus or ability to archive. we also demand a full of copy of that destroyed content. 

i know things like laws/responsibilities aren't exactly your first criteria but looking at the damage created I think it's a good idea to clean this up right.

**Comment by tx4x** [comment]
@BenGamma , @mattia-io 
Can you confirm there will be an email conversation to lift this or not ? Because we consider your recent actions as extreme hostile against, us as team, us as individuals and our users.

**Comment by tx4x** [comment]
@BenGamma  @mattia-io so we tried recovering at least our community efforts, that are lots of hours of other people btw. but as response David the guy in charge for our PP activities got just banned just for asking to recover the content.

with that you've cut any possibility to fix our bazaar payments, outstanding payouts from 6 weeks ago which is also a pretty tough disaster for some of us and quite some clients (asking us daily now). that are real people who have kids and so we had lend money from the bank now to pay them; no one of us can effort this behavior.

we asked for rectification but also the usual response : banned or no response. 

I honestly don't even know where to start, defamation, sabotage, tax, misleading information on purpose, misappropriate use of public funds, where does this stop ? 

when do you people start realizing that your actions have real impact, on real people. screwing small families life that way is unforgivable. please rectify, xamiro.dev@gmail.com

**Comment by martisj** [comment]
I have a pull request to allow saving discussions again.
