### ISSUE TITLE
Type 'undefined' is not assignable to type 'string'.  TS2345

### ISSUE THREAD

**Issue by seanbrookes** [OneArmyWorld/onearmy#397]
Hello,  I came across this project doing some research into DIY recycled plastic extrusion machines.

I've been developing web applications for long time so I was pretty excited to see you are using React / Node. Hopefully I can help out.

I cloned the repo to get up and running and ran into a typescript compile error in Action.tsx file in the pages/home folder:

```
Type error: Argument of type '{ resetPassword: true; actionCode: string | string[] | undefined; }' is not assignable to parameter of type 'IState | ((prevState: Readonly<IState>, props: Readonly<any>) => IState | Pick<IState, "resetPassword" | "actionCode"> | null) | Pick<IState, "resetPassword" | "actionCode"> | null'.
  Type '{ resetPassword: true; actionCode: string | string[] | undefined; }' is not assignable to type 'Pick<IState, "resetPassword" | "actionCode">'.
    Types of property 'actionCode' are incompatible.
      Type 'string | string[] | undefined' is not assignable to type 'string'.
        Type 'undefined' is not assignable to type 'string'.  TS2345

    58 |     } else if (values.mode === 'resetPassword') {
    59 |       this.handleResetPassword(auth, actionCode)
  > 60 |       this.setState({ resetPassword: true, actionCode })
       |                     ^
    61 |     } else {
    62 |       this.props.history.push('/')
    63 |     }
```

I'm comfortable with React but haven't worked much with typescript so it's not readily apparent what value actionCode should have.  Looks like it is referencing a query string parameter.

I was able to get it to compile by assigning a default prop to the argument passed to this.handleResetPassword:
```
this.handleResetPassword(auth, actionCode = '')
this.setState({ resetPassword: true, actionCode })
```
If this fix seems reasonable for this let me know and I'll push a PR for it.

thanks,
Sean

**Comment by kopecms** [comment]
sorry my bad.. #398
