### ISSUE TITLE
Create home page placeholder

### ISSUE THREAD

**Issue by chrismclarke** [OneArmyWorld/onearmy#40]
We have the background image for guest visitors but would also be good to have something more substantial to display to those we plan to share logins with. In the very least we need a button to direct to the new docs page for testing (instead of relying on automated redirect). Could possibly look to start on general home page mockup at the same time.

**Comment by chrismclarke** [comment]
less of a priority now subdomains used to render just one page on main site, but will still be needed as full platform develops

**Comment by mattia-io** [comment]
Hey chris.. what did you mean with this issue?

**Comment by BenGamma** [comment]
A placeholder is a default info to display when you don't have other.

At the time when chris open this issue, there was a big smiley on onearmy.world, now it is :
<img width="1672" alt="capture d ecran 2019-02-06 a 10 50 38" src="https://user-images.githubusercontent.com/4993215/52333422-7e10b680-29fd-11e9-92c8-a23000296df8.png">

The question here is : what do we display on this page ?
We can :
* add an authentification with login/pass like most of "in developement" site does.
* display an onboarding message like "here soon the new onearmy website" with a nice asterix 😁 ?
* leave it like this, we don't care that people can see the on progress work

**Comment by chrismclarke** [comment]
What @BenGamma said ^
The other option will be change the page which is the default 'home' redirect (e.g. start on the docs page)

**Comment by mattia-io** [comment]
Thanks @BenGamma option 2 sounds nice actually.. will ask mariska to do something for us.

**Comment by chrismclarke** [comment]
Just to keep things fresh, what did we decide for the community landing page? I know the main site will have the video, for community are we thinking some sort of general newsfeed, one of the other modules, or something entirely different?

**Comment by mattia-io** [comment]
community.onearmy.world will be the newsfeed but we have to think what will be the case for not logged in users

**Comment by chrismclarke** [comment]
I think we're currently headed in a different direction (show how-tos on beta version) so closing this for now (can revisit in future when working on community site)
