### ISSUE TITLE
TinyMCE plugins

### ISSUE THREAD

**Issue by tx4x** [OneArmyWorld/onearmy#404]
hi,
I guess you guys have now an idea about TinyMCE. For now we have custom image insert plugin (not finished : upload multiple pictures).
The next plugin candidates :

1. embed video : YouTube, ...
2. embed social : Instagram post, ... 
3. translate post : not urgent but enabling users to translate how-to articles seems needed at some point.

However, as always this adds js code to the editor but also for rendering. Any thoughts ?

**Comment by tx4x** [comment]
ah, i just realize, most plugins can come with lazy load for plugins, so it's not a real issue. I just want to know what's on the road map.

**Comment by BenGamma** [comment]
The editor is still not finished yet by the design team. We'll provide a proper roadmap and feature list when ready.
Youtube embed sounds like a strong candidate thought.
And what about user mentions discussed in #246 ?
Also is #349 done ? I haven't follow what happend there

**Comment by tx4x** [comment]
1. youtube: ok, i hope one those video players has it maybe
2. user mentions discussed in #246 : need an API to retrieve/resolve users, but i have to check it's there already
3. #349 : i dunno, it should but let me check against master again

**Comment by BenGamma** [comment]
> youtube: ok, i hope one those video players has it maybe
what do you mean ? if it has an integration for tinyMCE ?
2. user api in not on top of priority now but feel free to create a issue to suggest it. You can check with the label:Backend on issues list which are the one working on now

**Comment by tx4x** [comment]
good evening @BenGamma 

1. youtube: i'd prefer to make this as custom plugin. if it comes to media, v4 shouldn't fall short.. 

I recently pimped a react based video player to the max, which can deal with vimeo, youtube, images, from url, etc... what was more amazing it has a built-in playlist; I'd love that player can play hole categories or selected filters, for instance : recent posts (endless..., full screen).

2. to make backend work, please let's schedule for Friday, weekend a zoom meeting, i need directions and a few explanations about the platform :-) that would also allow me to fit the proposed filter system into the existing code base without too much hassle or noise. 

see you in a bit, i am a little short of time in the next weeks but i can take on non-critical tasks, editor, media player, ...

**Comment by tx4x** [comment]
hi Benjamin, 
i am afraid to tell you that I can no longer contribute into OneArmy. It was a team decision after putting all the facts together on the table from the last 12 months. Given the destructive nature of some of your guys, rendering endless hours of our and others content, just to please a few more unrelated community members how cowardly denounce our critics behind our back leaving no possibility to defense, well ... Also given the irresponsible nature of dealing v3 kit's issues, basically ignoring all the community reports as well ignoring other important things like the need of localizing PP or providing free trade brought us to the conclusion that it's not the time yet to help you. To me it's just a little criminal but plain irresponsible and selfish (i am not even mentioning the various defamation trials we had to suffer)!

however, we're still with PP, full - time, 5 seniors, but on a pretty much user-first base. by the end of the year i hope we can finish outstanding reports, data sheets and ready-to-go kits and to help people getting active but addressing all the unresolved issues first. 

see you in a while anyways :-)

**Comment by tx4x** [comment]
ah, fully forgot: i will post some snippets on how to use the proposed filter system in the discussions module.

**Comment by chrismclarke** [comment]
Yeah I'm back this week, just let me know if there's anything specific you want me to look at
