### ISSUE TITLE
PostTags component

### ISSUE THREAD

**Issue by BenGamma** [OneArmyWorld/onearmy#406]
Updated 18/04/19 (BenGamma)
### Description
We're gonna use a **PostTags** component to display all the tags contained in a post.

### Page related
Will be used in :
* How-to post view (#420) 
* How-to overview (#419)

### Mockup

<img width="168" alt="Capture d’écran 2019-04-18 à 14 19 28" src="https://user-images.githubusercontent.com/4993215/56360511-26ed4600-61e5-11e9-909f-4d7528b9cd0a.png">

### Build suggestion
The postTags component would take an array of tags as props and display them.

**Comment by nairolfo** [comment]
There is already a TagDisplay component that is used for example in the HowtoDescription <TagDisplay tagKey={k} key={k}/> Is the issue more related to the ability to save/retrieve the tags selected in the create view?

**Comment by BenGamma** [comment]
Hi @nairolfo 

No this issue is only related to the display of the tags. As we are still adjusting the backend, I would recommend you focus only on the frontend and use an array of tags in props as follow :
```
{
    label: 'Precious plastic',
    type: 'project',
},
{
    label: 'Machines',
    type: 'category',
},
{
    label: 'sheet press',
    type: 'secondary',
},
{
    label: 'hdpe',
    type: 'secondary',
}
```
Depending on the type you display :
- an icon on the tags with type `project`
- the tags with a different color

I suggest you create a new component `postTags` in `src/pages/common`.

Is that make more sense to you ?

**Comment by chrismclarke** [comment]
starting work on this now

**Comment by BenGamma** [comment]
closed with https://github.com/OneArmyWorld/onearmy/commit/9341f8f66f2376b5ee488e08a88727c3083db25d
