### ISSUE TITLE
badge component

### ISSUE THREAD

**Issue by BenGamma** [OneArmyWorld/onearmy#410]
### Description
A `badge` component to display multiple informations. Can be the status of a post or of a comment, later may for other usage.

### Page related
Will be used in :
* Discussion Q&A post (#409)

### Mockup

<img width="396" alt="Capture d’écran 2019-03-20 à 18 01 30" src="https://user-images.githubusercontent.com/4993215/54704077-5d7a6700-4b3a-11e9-9f21-d1f547b10d5a.png">

### Example

An [example of badge component here.](https://pricelinelabs.github.io/design-system/storybook/?selectedKind=Badge&selectedStory=Badge%20component&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) from priceline design system.

### Build suggestion

It contain an [Icon](https://github.com/OneArmyWorld/onearmy/blob/master/src/components/Icons/index.tsx) and some text. It is displayed only when the Q&A post is marked as solved by the creator.
The color will be set with the `bg` props and [like the Button component](https://github.com/OneArmyWorld/onearmy/blob/master/src/components/Button/index.tsx), the `glyph` props could be used to define an icon.

We'll need to add a field on the discussion object `is_solved`.

**Comment by tx4x** [comment]
eventually that's the time to introduce a flag, ie : LOCKED|PINNED|SOLVED,CLOSED etc..

**Comment by martisj** [comment]
I'll have a crack at this. @chrismclarke @BenGamma

**Comment by BenGamma** [comment]
Hey ! If you have a crack just go for it :)

>Figure out what exists in terms of differentiating between statuses?
Implement a simple typescript type like tx4x suggests.

For now we can consider 3 status : OPEN | SOLVED | LOCKED. 

> Display the badge on the discussion post

Yes, only for Q&A type post.

> Allow Post creator to mark as resolved. Only allow resolving (i.e. cannot unresolve a discussion) for now, to stay within the scope of the issue.

Yes, still need some clarification with design team thought. It is also linked to autenthication to only allow author to mark as resolve.

> (optional) inform the user that this action is not undoable.

Yes make sense but I would wait for the design to be ready

Thanks @martisj  :v:
