### ISSUE TITLE
Create@Discussions : Firestore errors

### ISSUE THREAD

**Issue by tx4x** [OneArmyWorld/onearmy#413]
good morning,
i wanted to proceed the works on TinyMCE, 
opening the page gives me endless errors: 

![image](https://user-images.githubusercontent.com/1205100/54519764-8e567280-4967-11e9-9681-11441d283a9c.png)

I dont know cypress but i am putting now my puppeteer-cucumber test suite locally in place to prevent this loss of time ;-)
g

**Comment by BenGamma** [comment]
As a reference, @rudolphfunk is working on #266 to implement unit test. I will merge #411 today, that looks to be a good starting point.
We want to avoid this loss of time, sorry for inconvenience.

**Comment by chrismclarke** [comment]
no idea what caused this, we really need to avoid errors falling into the main repos. Glad to hear @rudolphfunk picking up some of the testing, apologies I haven't found the time for it
