### ISSUE TITLE
how-to summary component

### ISSUE THREAD

**Issue by BenGamma** [OneArmyWorld/onearmy#421]
### Description
We're gonna use a **howtoSummary** component to allow user to easily navigate between the different steps that compose a how-to.

### Page related
Will be used in the how-to post view (#420) 

### Mockup
<img width="154" alt="Screenshot 2019-03-27 at 11 01 59" src="https://user-images.githubusercontent.com/17761877/55067363-dc622900-507f-11e9-83b2-8c7430f6a2e7.png">

### Examples
You can find component with similar behavior on the pages of [wikifab](https://wikifab.org/) or [wikihow](https://www.wikihow.com/Take-Care-of-Mini-Pet-Turtles)

### Build suggestion
Each step have an `id` html attribut which can be the title of the step. Then the component would reference an `#` anchor link to this id. No need to smooth scroll or any transition for now.

**Comment by sumedhan** [comment]
Hi 
Would love to work on this. Can I pick it up please?
Sumedha

**Comment by BenGamma** [comment]
Hi @sumedhan,
Yes, I add the label `in-progress` to the issue. Thanks !

**Comment by sumedhan** [comment]
The # link in react router causes the page to re-render. Looking for advice on how I can implement it.
[this package](https://www.npmjs.com/package/react-router-hash-link) seems like an option. 
Let me know how you want me to take it forward or if there is any other recommendation. 
Appreciate the guidance.

**Comment by BenGamma** [comment]
Hey @sumedhan 
I had a look at `react-router-hash-link` and it seems like a good solution, you can go with it :)

**Comment by BenGamma** [comment]
Closed with #435
