### ISSUE TITLE
Add filter samples to pages/Discussions

### ISSUE THREAD

**Issue by tx4x** [OneArmyWorld/onearmy#424]
just for house keeping for a PR which demonstrates the use of the filter system in pages/Discussions.

**Comment by tx4x** [comment]
hi,
can someone fix the discussions mock data ? i need each post to have valid tags (matching filter bar select values) and categories and project if possible.

btw, the firestore exceptions are really annoying, no fun to code here

**Comment by tx4x** [comment]
ok then, closing. thanks for your time ..

**Comment by chrismclarke** [comment]
Hey man, apologies I've been away running a workshop in South Africa so a bit slow to get to issues. I'm still really keen for the filter system (both for this project and another one I'm working on) so happy to help try get things running more smoothly for you. What exceptions are firebase throwing?

As for the mock data, I think the format of the data should be correct but awaiting on updates to display components. Although I'm guessing to test filters it might be easier for you to have some more specific data (i.e. less lorem ipsum, more actual tags etc.?)

**Comment by mattia-io** [comment]
Hey @tx4x the latest signed off prototype can be found here
https://www.figma.com/proto/OZ5xbZYR4ZKNBijrs9kPJnbu/OneArmy-Platform?node-id=458%3A0&viewport=-1426%2C242%2C0.0625&scaling=scale-down-width

**Comment by BenGamma** [comment]
This is on hold for now. Will reopen if appropriate in a close futur.
