### ISSUE TITLE
Questions regarding the platform

### ISSUE THREAD

**Issue by ThomasRoest** [OneArmyWorld/onearmy#425]
Hi, I was thinking about contributing but I still have some questions 

1. Is there already a live v1 that is being used? It doesn't look like it at https://onearmy.world
If not, when are you planning to release a v1? 

2. I've read the descriptions of the platform and its functionalities. But I'm still not sure what users will actually be doing on this site. Is it uploading tutorials, chatting, posting forum threads, or articles? 

Thanks!

**Comment by chrismclarke** [comment]
Hi, we have a dev site: https://dev.onearmy.world/ but it still needs quite a bit of development. There's also a prototype that can be viewed at: https://www.figma.com/proto/OZ5xbZYR4ZKNBijrs9kPJnbu/OneArmy-Platform

As for your second point, most of the things mentioned plus anything else felt required to help sustain a strong community (additional modules planned for events, creating sub-organisational units and a few others)
