### ISSUE TITLE
Display data from firebase

### ISSUE THREAD

**Issue by BenGamma** [OneArmyWorld/onearmy#43]
display tutorial list and tutorials from firebase database instead of mocks data

**Comment by BenGamma** [comment]
related to review #48

**Comment by BenGamma** [comment]
For now I'm using a pretty "simple" method to get data  : on the `componentDidMount` event from the pages/Docs/Docs.tx file (which is the parent of all the /docs pages) , i'm sending a call to firebase db to get all the tutorials entries. Then I pass the `allTutorials` data as props to `pages/Docs/Content` components and display them.

It's enough for now that we don't have to much database calls, but in the future, we probably want to use a more efficient way to get/write datas.

An example using mobx store, signals, actions, and others good practices :
**Code sandbox profile page display**
* https://github.com/CompuIves/codesandbox-client/blob/master/packages/app/src/app/pages/Profile/index.js
* https://github.com/CompuIves/codesandbox-client/tree/master/packages/app/src/app/store/modules/profile

**Comment by chrismclarke** [comment]
I think this is fine for now. In the future we will likely add utilities to persist data locally so that even if there are a lot we don't need to worry as they'll only ever be downloaded once (and only updated when content updated).  Closing now as key points merge into #73
