### ISSUE TITLE
[bug] Get user avatar url outside the Avatar component

### ISSUE THREAD

**Issue by BenGamma** [OneArmyWorld/onearmy#433]
**Describe the bug**
Each time we use the Avatar component, a request is made to the backend to get the user using the userId. [See here](https://github.com/OneArmyWorld/onearmy/blob/c8e9b958f275173cd689abd51b49bbb1979464e2/src/components/Avatar/index.tsx#L36).

**Expected behavior**
The avatar component should instead take a `src` prop and display it, but not making a db request.
Because then it result on a request on each render, which multiplied by the number of users and component uses would be a looooot 😅

**Comment by chrismclarke** [comment]
The problem with always taking a src is that the src needs to come from somewhere. The simple case is to just save the src when saving the rest of the data (e.g. when a user creates a 'how-to', save the userID and user avatar url, however if the user ever changes this then you'd have to find all the places to update.

A better option would be fixed urls where we know a users avatar is always at 'https://example.com/{userID}/avatar.jpg'..
I'm not sure how easy this is to do but I will look into it tomorrow. 

This might not still be sufficient as we may find ourselves wanting to pull a bit more user information with the id (e.g. their @mention-name), in which case we should instead think about ways to make more efficient generally (opened up an issue for this for #443 )

As it happens I came across the same challenge when working on the user-profile module and so have added a small commit that enables use of either url or id for request. Will make a pr with the rest of the module by the end of the weekend.

**Comment by BenGamma** [comment]
Codesandbox seems to manage all the profile informations with signals from the mobx store which make sense. Check [this example](https://github.com/CompuIves/codesandbox-client/blob/4032aad4e2c38a98cc334680eccb35db5ae554bd/packages/app/src/app/pages/Profile/index.js#L35) from their Profile page, and in their store [here](https://github.com/CompuIves/codesandbox-client/blob/4032aad4e2c38a98cc334680eccb35db5ae554bd/packages/app/src/app/store/modules/profile/index.js#L34) they define the `profileMounted` signal.

It may be a starting point for this but I haven't dive into yet.

**Comment by chrismclarke** [comment]
implemented as described (userID passed to avatar component which links directly to storage object). closing
