### ISSUE TITLE
Add support for internationalisation

### ISSUE THREAD

**Issue by chrismclarke** [OneArmyWorld/onearmy#45]
Plentry of tools and examples, just need to put in and add to contribution guides so people know how to use

**Comment by chrismclarke** [comment]
Popular packages seem to be between react-i18next and react-intl. Suggest we pick one and try put together a working component example

**Comment by chrismclarke** [comment]
hey @darrylAlexander , thanks for taking this on, let me know when you've created a branch to work on and I'll populate a placeholder page and component that you can use for testing

**Comment by darrylAlexander** [comment]
I have pushed a demo using the react-i18next components. It's really basic just to see how easy it was to get going and the basics, has lots of features and other packages to supplement it.

Next, I am going to have a look at using react-intl to excess whether one is better than the other and what felt easier to setup.

**Comment by chrismclarke** [comment]
looks good and works well, I'd be happy to go with either system so will be interested to hear what your preference is. You're right that we will definitely want to move files into a separate folder (most likely assets/i18n/es.json for example), as a personal tip, if there is something that you plan to do later you might find it good to add the word 'TODO' at the start of your comment to highlight it and make it easier to search for outstanding/forgotten issues across all files.

**Comment by darrylAlexander** [comment]
I've been taking a look at react-intl and it works very well with the project based on the current locale. It comes with the ability to format dates, currencies and the like... whereas i18next requires some extra setup with moment.js for this to work but still supports this.

That being said its very difficult using the API of react-intl compared to using react-i18n as it was originally built to use reacts propTypes. It does support TypeScript types but I wasn't able to get it to dynamically change the language using a button. This might be because I'm a noob to react and typescript though. I searched around and others seemed to be struggling to or used cookies and a refresh to set the language. [This article](https://www.smashingmagazine.com/2017/01/internationalizing-react-apps/#top) is a good tutorial of using react-intl.

My personal preference would be to use react-i18next because i found it more intuitive to use but it might be bulkier in terms of storage than react-intl if we start using all the features.

Does anyone have a preference? @chrismclarke would you still be happy to go with react-i18next?

**Comment by chrismclarke** [comment]
Thanks for looking into this, I know typescript often has problems playing nicely and although there are always ways to force/work around it's probably not worth getting to hung up on. Let's go ahead with react-i18next.

**Comment by darrylAlexander** [comment]
I have been testing getting json files working. I came across a barrier that TSLint is currently rendering JSON files as TypeScript even if you exclude it in `tslint.json`. The work around is to allow no unused expressions but this means the linter won't pick up unassigned or unused objects. See more at [tslint issue 3957](https://github.com/palantir/tslint/issues/3957).

I've left it in for now so I can progress the internationalization.

**Comment by BenGamma** [comment]
Hey Darryl 🖖 
So after some time working on the project, would you say that the fact that we use typescript is slowing you down, or make the development more complex ?

**Comment by darrylAlexander** [comment]
Hey @BenGamma 

I would say that TypeScript hasn't necessarily slowed me down because I'm also learning to use TypeScript and React. I used the JavaScript prototyping style before this so I've had to update my JavaScript too. 

I feel as though you've picked a good set of tools, as a developer in this modern age, I would have expected package management, build scripts, test suites and linters. It just means that someone, who has had to get their skills up to date in the JavaScript world (like me), takes a bit longer but I'm learning and soon I'll be pro.

**Comment by chrismclarke** [comment]
The json import issue is an annoying one, I thought in the dev branch I had put both tsconfig and tslint files to allow import so if possible could you try merging the most recent versions into your branch and see if the issue persists?

**Comment by chrismclarke** [comment]
also... 

> test suites

Something we're really lacking and I always find it hard to prioritise (but do value), so if somebody wants to take on the challenge they'll be most welcome!

**Comment by darrylAlexander** [comment]
Thanks for the pointer, I'll take a look at dev and merge the most recent in. I will try and get some unit tests in for this issue. For the next steps I was going to make a language button component and import that into the page, that way all pages will just need to import this component to get the language functionality.

**Comment by BenGamma** [comment]
Hey Darryl,
Happy new year too !

Thanks for the work, I'm going to test it in the next days and come back to you soon

**Comment by darrylAlexander** [comment]
Hi @BenGamma,

I've updated this to include unit tests but these are only success cases and initial configuration for using jest. This should help going forward with testing.

The next step for this component as hinted above is to move away from the three buttons and instead have the component as one button that selects from a list so a select box basically.

I welcome your testing and feedback from this. Cheers.

**Comment by BenGamma** [comment]
I just review the `translation` branch and it is a good example for futur implementation of a translation system. The unit test are also a good getting started. Thanks for that @darrylAlexander 

If you are still willing on working on this, what would be nice to do is to combine this implementation of translation with our state management mobx. So when you click on the translate button, the state of the all app is updated, while here it's updating the component and his parent. After a quick googling [this ressource](https://itnext.io/ultimate-localization-of-react-mobx-app-with-i18next-efab77712149 and especially) seems to be usefull, which include [this example](https://codesandbox.io/s/n5jmk0q69j) of mobx implementation with i18next.

**Comment by BenGamma** [comment]
More globally about the translation system, I'm wondering now if we should implement the translation system straight or if we should keep it on the side as we are still working on the design of the plateform.
We need to take in consideration that as a lot of the content of the site (e.g. post, comments, etc) will be populated by users, it will be difficult to translate on the go. But for the part that will be from the admins, it may be easier. 
Should we put this issue in backlog for now or keep working on it @mattia-io ?

**Comment by darrylAlexander** [comment]
I would be more than happy to continue on this but I guess if @mattia-io decides to put in the backlog it might be better for me to chip with something else on the project.

**Comment by BenGamma** [comment]
@mattia-io test for notifications 😅

**Comment by mattia-io** [comment]
Hey guys, sorry for slow response.. So when it comes to translation we're always battled with this dilemma. Multilanguage always sounds nice as you can reach more people that don't speak english. However, at the same time this also means prompting users to post content in their own language, content which we can't do much with as we (and most of the other users) don't speak their language. This would clutter our platform. However, translation could be very useful for the global site where we connect to first time users, press, curious mind etc.. 

For the moment, I think translation should be put on hold in favour of more urgent must-have components for the One Army platform. @darrylAlexander do you feel like grabbing another issue from the tag "good first issue"?

*And thanks for all the work you put into the translation so far 💪

**Comment by tx4x** [comment]
what's the final take now ? I'd like to finish the editor component and I think at least core - ui widgets should have a minimum of localization, ie: upload image, ok, cancel, etc...
needless to say but I strongly disagree of course again that PP should be limited to the western country folks. more than 50% of our users just don't speak english
g

**Comment by mattia-io** [comment]
Hey @tx4x I think for now we'll have to prioritize english given our limited dev resource. We want to bring the platform to life first then, when we have time and devs/des at hand we'll tackle other languages.. Thanks man!
Big up!

**Comment by tx4x** [comment]
ok, thanks. just to complete : please check transifex (awesome service, for peanuts). otherwise check Dojo (BSD)  -1 toolkit, it's all there when it comes to basic ui locals. For now, I just use a place holder function in src/i8next or wherever ;-)

**Comment by chrismclarke** [comment]
Thanks everyone for the input in this. I've tried to summarise the key discussions in the wiki, and will close this thread for housekeeping purposes. 

https://github.com/OneArmyWorld/onearmy/wiki/Translations

Still feel free to add your comments wherever desired, and I hope we will be able to come back to this in the not-too-distant future.
