### ISSUE TITLE
Use durationSincePosted in how-to post

### ISSUE THREAD

**Issue by BenGamma** [OneArmyWorld/onearmy#458]
See in [PostList/ListRow/index.tsx](https://github.com/OneArmyWorld/onearmy/blob/b57d427819f892a5d1be69bb10b2a40dd0dc7fa8/src/pages/Discussions/PostList/ListRow/index.tsx#L32) `durationSincePosted` function.

Use the same function in [PostView](https://github.com/OneArmyWorld/onearmy/blob/b57d427819f892a5d1be69bb10b2a40dd0dc7fa8/src/pages/Howto/Content/Howto/HowtoDescription/HowtoDescription.tsx#L38) to display the duration when the post was made.

**Comment by tanvirraj** [comment]
anyone working with this issue? I am interested

**Comment by BenGamma** [comment]
Hi @tanvirraj ! Nope you can go for it. Let me know if you start so I'll add the `in progress` label :v:

**Comment by tanvirraj** [comment]
@BenGamma created a  [PR](https://github.com/OneArmyWorld/onearmy/pull/469) for this issue

**Comment by BenGamma** [comment]
Merged with #469
