### ISSUE TITLE
Refactor index.ts

### ISSUE THREAD

**Issue by chrismclarke** [OneArmyWorld/onearmy#46]
Decided sensible model is to include one index.tsx at a component/page/model group level (and not for individuals) to handle simple import/export

**Comment by chrismclarke** [comment]
At the same time can also look at named/default exports. Things like pages should all be named exports (can use @withRouter decorator where previously passed through function). Page content will probably be default (or otherwise should reconsider naming convention)

**Comment by BenGamma** [comment]
Not clear what's happening here, should we consider adding a section in the https://github.com/OneArmyWorld/onearmy/blob/master/CONTRIBUTING.md#--project-structure to explain the naming convention ?

**Comment by chrismclarke** [comment]
I think since this issue was first open so much has changed with the structures that not entirely relevant. Closing for now and can review overall folder structures and consistency after styled-system implementation
