### ISSUE TITLE
v0.3.0 release process

### ISSUE THREAD

**Issue by BenGamma** [OneArmyWorld/onearmy#466]
1) Define the subdomain alpha / beta / test / begin .onearmy.world

2) link branch `v0.3.0` to the subdomain. To do that I would suggest to create a tag with the subdomain same. On each push of this tag, the tagged branch is automatically deploy to the subdomain.

**Comment by chrismclarke** [comment]
I have no issue with release/tag versions and automatically deploying, however just to check, are you suggesting we also have an entirely separate database/user auth system for each release or can we use the master database (as we do for the live production site)?

**Comment by BenGamma** [comment]
My idea was to use the master database yes :)

**Comment by chrismclarke** [comment]
Ok yeah I can get that done

**Comment by BenGamma** [comment]
We're going to release the v0.3.0 on the domain https://alpha.onearmy.world

@chrismclarke let me know if I can be in any help to setup the subdomain and/or the tag deployment. 

The idea is to create a tag `alpha`, and each time this tag is pushed to a new branch/commit, the deployment to https://alpha.onearmy.world starts automatically.
