### ISSUE TITLE
Link username and avatar to created by message 

### ISSUE THREAD

**Issue by chrismclarke** [OneArmyWorld/onearmy#467]
Currently just shows 'by' and blank. Should show username and avatar.

**Comment by BenGamma** [comment]
Should show only username. eg [mockups](https://www.figma.com/file/OZ5xbZYR4ZKNBijrs9kPJnbu/OneArmy-Platform?node-id=3370%3A5028).
Done with https://github.com/OneArmyWorld/onearmy/commit/6d13801673440cd5f82115ee6c19d466165604af
