### ISSUE TITLE
[bug] - Final form arrays poor performance

### ISSUE THREAD

**Issue by chrismclarke** [OneArmyWorld/onearmy#483]
**Describe the bug**
You can see when adding/removing steps how janky the animation is. This is due to heavy re-renders and checking by final form

**To Reproduce**
Add remove how-to step or add a console log during the render method to count

**Expected behavior**
Minimal renders

**Additional context**
Common issue, discussion and potential solutions:
https://github.com/final-form/react-final-form-arrays/issues/22
https://github.com/final-form/react-final-form/issues/336
https://github.com/final-form/react-final-form/issues/190
https://codesandbox.io/s/32r824vxy1

**Comment by manzoorwanijk** [comment]
Any update on this?
The performance is very poor. I removed all the fields except the array field (with just two sub fields) and it is still the same.

**Comment by chrismclarke** [comment]
As a quick update, 3 months later and issues still open but some people say that latest versions should add some improvement. We are stuck on v3 so it would be worth somebody testing whether upgrade to v6 can be done without breaking too much!
