### ISSUE TITLE
[feature request] - ability to add caption to images

### ISSUE THREAD

**Issue by chrismclarke** [OneArmyWorld/onearmy#494]
**Is your feature request related to a problem? Please describe.**
Requested from user feedback

**Describe the solution you'd like**
Simple text box under image upload or lightbox popup to add caption

**Describe alternatives you've considered**
Not having it

**Additional context**
I think it would be a good addition and quite quick to implement, just need to decide on the UI/UX side

**Comment by RickyMed** [comment]
I would like to tackle this issue if that's fine.

**Comment by BenGamma** [comment]
merged with #535
