### ISSUE TITLE
[Enhancement] - Improve how-to image display

### ISSUE THREAD

**Issue by chrismclarke** [OneArmyWorld/onearmy#495]
**Is your feature request related to a problem? Please describe.**
Currently all pictures display at maximum size, and feedback is saying this is too big.

**Describe the solution you'd like**
Either set a max width for images and use the same lightbox functionality to open larger on click as used in the how-to create page, or possibly have one large image and smaller thumbnails of others which can be clicked to enlarge

**Additional context**
When implemented would be good to give feedback through userreport also (Louis idea).

**Comment by tudi2d** [comment]
Hello! I would like to work on this issue. I read through your Contribution Guideline, took a look at the code of the project and think that I can implement a solution for this. The first approach you suggested sounded good so my idea was to change it from this...

![image](https://user-images.githubusercontent.com/8904624/62005528-dfa41900-b134-11e9-8d77-4d097c258c01.png)

... to this ...
![image](https://user-images.githubusercontent.com/8904624/62005515-bc796980-b134-11e9-979e-aa4e610add03.png)

... and add the Lightbox like it was done in the ImageInput component. 
Looking forward to your feedback and I would be happy to contribute! :) 

@mattia-io (The guideline said I should mention you)

**Comment by mutalis** [comment]
@chrismclarke @tudi2d 
Additional tip: You can make your website faster and less data-hungry by using the right file format for images.

In few words use the correct format — SVG or JPEG

This video shows simple techniques to identify problematic images, and then quickly and easily optimize them to the most suitable format.

https://www.youtube.com/watch?v=8VoCua-dEu0

**Comment by chrismclarke** [comment]
Haha, saw that video last week too! Agree SVG/JPEG is the way to go, up till now we've mostly avoided PNGs and have automated client-side compression for all the images as they are uploaded. I think there's also an open issue for converting videos, although at this point we're simply not using them.

I think simply adding a max width and lightbox feature would definitely be a good start, so please feel free to try and implement that and make a PR when successful.

**Comment by chrismclarke** [comment]
I could also imagine perhaps adding a breakpoint for larger screens where text is shown beside the image might also be nice, although should probably check with @BenGamma and the design team in case they have already drawn up designs.

(example - main image next to text, additional images as thumbnails which could also be opened)
![image](https://user-images.githubusercontent.com/10515065/62330713-651b2680-b4b1-11e9-91e3-70eda95ed89d.png)

**Comment by tudi2d** [comment]
@chrismclarke Thanks for the feedback!

I created a pull request, which adds a fixed width as well as a lightbox. I also like the idea of displaying images on the right hand site, but I think this might be part of a new enhancement (Users might want to deicide by them self if a image should be displayed on the left, right or in the center instead of displaying every image on the right hand site) :+1:

**Comment by BenGamma** [comment]
merge with #536
