### ISSUE TITLE
[bug] - Service worker not caching images

### ISSUE THREAD

**Issue by chrismclarke** [OneArmyWorld/onearmy#503]
**Describe the bug**
Service worker caches site so core loads offline and database has separate offline sync to populate data, however currently retrieved images are not cached

**To Reproduce**
Visit site offline

**Expected behavior**
Previously loaded images should be cached

**Screenshots**
![image](https://user-images.githubusercontent.com/10515065/58872414-dc078f00-86bb-11e9-9d6c-d497960a50b6.png)

**Comment by kopecms** [comment]
only thing I could came up with (beside writing custom service worker) is setting cache-control while saving file in firebase. I have tested it on chrome and it's working

**Comment by chrismclarke** [comment]
oh cool, yeah just tested also and seems working. Probably a caching issue as suggested thanks for testing, closing here
