### ISSUE TITLE
Map Module Scaffolding

### ISSUE THREAD

**Issue by chrismclarke** [OneArmyWorld/onearmy#505]
### Description

The map module is getting ready for active development. Whilst still waiting for final specs, there's another to getting going with. Previously some map components were used in the events page which need tidying before reuse, and then a base structure put in place to make it easier for devs to work with. Specifically:

- [x] Add map page container
- [x] Add map store
- [x] Define map pin data structures
- [ ] Set bindings to read/write map pins to DB
- [x] Add mock data
- [ ] Add backend function to pull DH site data
- [ ] (?) Add backend function to write DH site data

**Comment by chrismclarke** [comment]
Added the main page container, a separate Map View container and inside direct hookup to leaflet.

Pulled the legacy map pins and just hardcoded them for now, and added a small script to convert the data format to match what we expect the final db will look like (pending whatever people decide)

Haven't got round to adding the binding for adding more pins to the DB yet, but guessing this should hopefully be enough to start with styling, clustering, filtering etc.

**Comment by BenGamma** [comment]
Now implemented with #517 
Separate issue created for db related question #518 
Closing.
