### ISSUE TITLE
[feature request] Make at least one image required per step

### ISSUE THREAD

**Issue by pmcp** [OneArmyWorld/onearmy#511]
### Description
Every step in a how to article should have at least one image. 
If a user creates a step, he can't publish if there isn't at least one picture in that step.

### Page related

Will be used in :

- How To

**Comment by kopecms** [comment]
Why? imo you don't need pictures to explain stuff. Also makes creating how to less user friendly. I would focus on creating a edit page for how to rather than implementing this restriction (then user can add image if requested in comments eg)

**Comment by pmcp** [comment]
You are correct from the point of view of the editor, but it's an feature to make the how to's easy and attractive for the other users. Up for debate ofcourse :)

**Comment by catx23** [comment]
i left some more food in this regard : https://davehakkens.nl/community/forums/topic/alpha-review/#post-145359

i agree, image should be optional, and it should be only one of many types you could use there; even code would be cool.

**Comment by catx23** [comment]
ok then. i couldn't see any plugin/addon infrastructure code enabling 'onearmy' campaign statements about extend-abilities; where or how can we integrate the addons mentioned above in the forum entry ? 
thanks

**Comment by BenGamma** [comment]
@catx23 I'm not sure to understand what you are talking about. You want to propose a feature request ? If so feel free to use our issue template to describe your idea.

**Comment by BenGamma** [comment]
Closing this issue for now since it's not a high priority feature

**Comment by catx23** [comment]
@BenGamma , feel free to follow the [mentioned forum post](https://davehakkens.nl/community/forums/topic/alpha-review/#post-145359). More or less we have quite a different point of view on what the platform has to provide and what not but also the tools and frameworks; also enabling the platform to be used for other projects. All we need is a way to show & integrate community modules/apps to the extend PP eco system as you exactly pointed out in the onearmy - promo video. Would be great to know at least that this is actually going to happen or not. 
thanks in advance.
