### ISSUE TITLE
[feature request] Remove the "Low / Normal / High" option for uploaded images

### ISSUE THREAD

**Issue by pmcp** [OneArmyWorld/onearmy#512]
### Description

User can now choose the compression when they upload an image. We want to make it dummy proof for the user, and leave this choice out. We choose the best compression / size of the image and go with that. We still show them how much it is compressed and the impact that has on environment, but just take away the choice for the user.

### Page related

Will be used in : How To (edit)

**Comment by chrismclarke** [comment]
sounds good to me, what do you reckon would be the best size of images to go for?

**Comment by BenGamma** [comment]
We would use the low conversion rate by default

**Comment by Andrux51** [comment]
Hello, I'm new to the project and planning to start by tackling this feature. I have a pull request coming in a few minutes.

**Comment by chrismclarke** [comment]
Hey @Andrux51 , welcome! Thanks for the PR, we try to review every Tuesday so will hopefully be able to feedback around then.

**Comment by Andrux51** [comment]
Sounds great!
