### ISSUE TITLE
Add Feedback Button (Typeform)

### ISSUE THREAD

**Issue by pmcp** [OneArmyWorld/onearmy#514]
### Description

A feedback button that connects with Trello. It's made in Typeform and can just be implemented in the website. Code is here: https://codepen.io/pmcp/pen/vqObPb

Should appear on every website, position absolute against the right side of the viewport.

The Typeform takes two parameters in the url: the url of the page and extra tech info about the user session. Both can be captured in javascript and added to the url of the form. More info on the codepen.

### Page related

Will be used in :

- All pages

**Comment by BenGamma** [comment]
Created a feedback button merged in #521 , for now simple external Link to the typeform.
We may want to use hidden-fields and/or [more advanced features](https://www.typeform.com/help/hidden-fields/) provided by typeform in the futur. Leaving here as a note.
Closing.
