### ISSUE TITLE
Want to limit query when fetching list of all tutorials

### ISSUE THREAD

**Issue by BenGamma** [OneArmyWorld/onearmy#60]
This has already been mentioned but just to reiterate, as the total number of tutorials grows we will want to limit this so not all tutorials are brought in when the page is loaded (either have a ‘more’ button or load on scroll). This should only become a priority once we actually have more tutorials than what we would want the limit as (say 20?)

**Comment by chrismclarke** [comment]
Just to add some perspective, we will get billed for every item that is returned from a query (regardless of how big the collection is, returning 20 items from a list of 2,000,000 still will only count as 20 read operations). We can get 1,500,000 reads per month free across all operations so unlikely that we will be exceeding too quickly (assume each user pulls the full list of 20 a couple times per session in navigating back and forth or applying filters, and maybe we have a few hundred users daily). 

This could however get messier when looking at the thousands of map points and so more advanced strategies will be implemented for larger datasets (see #73).

**Comment by chrismclarke** [comment]
Given new db optimisation (#73) I think actually retrieving all documents and caching won't be so bad. Can review again once we start having more users, documents etc. but closing for now
