### ISSUE TITLE
Clicking create tutorial page starts scrolled down

### ISSUE THREAD

**Issue by chrismclarke** [OneArmyWorld/onearmy#62]
If you've scrolled to click the 'create tutorial' button then the page retains its current scroll position on load, meaning that the user then has to manually scroll to the top to view step 1
child of #3

**Comment by glauberramos** [comment]
I tested that on mac - chrome and it didn't happen. It's working fine. Which browser and os did you use to test?

**Comment by chrismclarke** [comment]
Thanks for testing, I think @BenGamma  actually fixed this (I see a scroll-to-top component that is triggered on page change). Can this now be closed?
