### ISSUE TITLE
Hide navigation on single component view

### ISSUE THREAD

**Issue by chrismclarke** [OneArmyWorld/onearmy#84]
Mockups have been produced so would be good to get testing on live site.

When creating also need to take into consideration single component display mode (or perhaps link to router layout) - this won't affect the nav themselves but will likely need to be brought into the router component

child of #106
requires #108

**Comment by chrismclarke** [comment]
merge into #108

**Comment by chrismclarke** [comment]
splitting this issue, the creation of navbars is now part of #106 , this can serve as a reminder that we will want to hide navigation entirely when we have chosen just to display a single component (like how the documentation component is displayed at documentation.preciousplastic.org)

**Comment by BenGamma** [comment]
Dave and @mattia-io decided that we will non longer update documentation.preciousplastic.com to avoid confusion between the One Army plateform and PP. Closing.
