### ISSUE TITLE
Improve and modify documentation database structures

### ISSUE THREAD

**Issue by chrismclarke** [OneArmyWorld/onearmy#86]
A few minor issues:

1. Each document is sent with a single field called 'values' which contains all the data. Whilst the database will still create indexes for searching within this values map field it is slightly inefficient and also limits query ability for child fields. Instead the document should contain all the fields which are currently assigned to values.

2. Let firebase automatically name documents. This will be more resilient against people changing slugs. A random key will be generated, so when searching for a doc we will need to run a query (e.g. WHERE slug == ...). As the slug is indexed this will be just as fast as returning the document by key alone.

3. Tags should probably either be stored in a single array of strings (i.e. tags: ['tag1','tag2','tag3']), or a json object with tags as keys and boolean for selected (i.e. tags:{tag1:true,tag2:true,tag3:true}).
Theres pros and cons to each, particularly if we plan to filter client or server side and by just one or multiple strings. I personally think probably the second case would be better, although this article promotes the first: https://firebase.googleblog.com/2018/08/better-arrays-in-cloud-firestore.html

4. Tags should have their own entry in the database as they are likely to persist across all section. I would suggest that each tag be composed of [label, collection (e.g. 'machines'), imageUrl]. This way we could have a visual collection of tags, organised by different categories. 

5. All database entries should contain 'date_created' and 'date_modified' numeric timestamps to help make it easier to order in the future. 

6. Numeric fields appear in the database as string. This might be a problem with the input field or logic somewhere else. We should ensure data is in the correct format to allow for better querying and avoid future bugs related

@BenGamma, let me know if you want me to implement this or if you want to yourself.

child of #3

**Comment by BenGamma** [comment]
related to #54

**Comment by BenGamma** [comment]
To add to the points :
1. This is due to the use of react-final-form, need investigation on how the form data can be modified before send to firebase 👉 https://github.com/final-form/react-final-form

2. I agree on that, but I think we still need to keep the slug understandable as it is used in the url. Example : http://onearmy.org/docs/how-to-do-extrusion is more understandable when you read the url than http://onearmy.org/docs/ie3bf56cd

3. & 4. For sure, I did a quick a dirty implementation of tags for now

5. related #54 

6. We use string for now for example for the tutorial_price to let the user add his currency(€,$...), as we haven't figured out for now a better solution to handle multiple currencies. Same with the time value, to allow user to add hours/days/week directly in the field.

**Comment by chrismclarke** [comment]
1. I've had similar problems in the past with form packages. If there is a quick/easy solution to format correctly then great (e.g. adding certain props to the form element), if not I would suggest you do the following: 
- create a new folder within docs called 'hacks'
- add a function inside called something like 'formatFormDataForDBUpload()'
- use the function to manually update field types. You will likely have to use 'if' statements if the field was optional and can convert strings to number using the Number() constructor (better than parseInt or similar), e.g. numVar = Number(stringVar).
The reason to separate out like this is as this is a bit of a messy workaround we can isolate and potentially replace in the future if a nicer solution becomes available. 

2. Yes, the slug will be what we save in the database as slug (the user will never know the id), all that it means is when you navigate to docs/how-to-do-extrusion there is a single database query to get the document (e.g. ref= db.collection("Tutorials).where("slug","==","how-to-do-extrusion).limit(1); ref.get()... you'll have to parse the returned result in the same way you did full collection list)

5. Just add an extra field to populate the timestamp, it should be in a universal timestamp format (e.g. _date_created = new Date()
_date_modified = new Date()

**Comment by chrismclarke** [comment]
1, 5, 6 now implemented, wip on 2,3,4

**Comment by chrismclarke** [comment]
2 implemented and 3-4 merge into #88. closing
