### ISSUE TITLE
ensure all material elements are imported correctly

### ISSUE THREAD

**Issue by chrismclarke** [OneArmyWorld/onearmy#93]
A slightly tedious task as likely people will consistently auto import from named imports
Bad:
`import {Button} from '@material-ui/core'`
Good:
`import Button from '@material-ui/Button`
(for tree shaking reasons, will see noticeable improvement in compiling time)

Suggest that periodically search across files for "} from '@material" to pick up first case and correct

This issue shouldn't be closed

**Comment by BenGamma** [comment]
Don't you think this informations would deserve a section in the wiki instead of an issue @chrismclarke ?

Keep issues open as informations seems quite odd to me. If it is an important information or behavior that deserve to live in the wiki to me.
