### ISSUE TITLE
Create new tutorial file download mechanism that supports multiple files

### ISSUE THREAD

**Issue by chrismclarke** [OneArmyWorld/onearmy#94]
Files are now saved as an array of objects contain more meta data. On tutorial page there should be a component that shows the available files and give option to download
child of #3

**Comment by chrismclarke** [comment]
have updated to use new system but still only downloads a single file (latest entry) - lowering priority

**Comment by BenGamma** [comment]
Fixed with https://github.com/OneArmyWorld/onearmy/pull/195
Closing.
