### ISSUE TITLE
Add guiding principles to contribution docs

### ISSUE THREAD

**Issue by chrismclarke** [OneArmyWorld/onearmy#97]
Recently initiated discussion on Skype to help address some questions/general guiding principles. These should be capture, shared, reviewed and made accessible to anybody involved with the platform

**Comment by BenGamma** [comment]
Solved with our [contribution guide](https://github.com/OneArmyWorld/onearmy/blob/master/CONTRIBUTING.md) and [wiki](https://github.com/OneArmyWorld/onearmy/wiki)
Closing.
